-- name: GetHerde :one
SELECT *
FROM HERDEN
WHERE ID = $1;

-- name: ListHerden :many
SELECT H.*,
       COALESCE(S.BEZEICHNUNG, '') AS STALL_BEZEICHNUNG,
       COALESCE(S.STALLNUMMER, 0)  AS STALLNUMMER
FROM HERDEN H
         LEFT JOIN STALL S ON H.ID_STALL = S.ID;

-- name: GetSilo :one
SELECT *
FROM SILO
WHERE ID = $1;

-- name: ListSilos :many
SELECT ID,
       SILONUMMER,
       PERSONENNUMMER,
       ID_LIEFERANT,
       COALESCE(BEZEICHNUNG, '') AS BEZEICHNUNG, 
       COALESCE(INVENTURDATUMALT, '0001-01-01') AS INVENTURDATUMALT, 
       COALESCE(INVENTURDATUMNEU, '0001-01-01') AS INVENTURDATUMNEU, 
       MAXFUELLMENGE, MINFUELLMENGE, INVENTURFUELLMENGE, AW
FROM SILO;

-- name: ListEilager :many
SELECT ID, LAGERNUMMER, KZ, 
       COALESCE(BEZEICHNUNG, '') AS BEZEICHNUNG, 
       COALESCE(LETZTE_BUCHUNG, '0001-01-01') AS LETZTE_BUCHUNG, 
       JUMBOS, XL, LARGE, MEDIUM, SMALL, VOLLEIKG, AW, KLASSE6, KLASSE7
FROM EILAGER;

-- name: GetPerson :one
SELECT *
FROM PERSON
WHERE ID = $1;

-- name: ListPersonen :many
SELECT *
FROM PERSON
WHERE (KZ IS NULL OR (KZ != 'A' AND KZ != 'F'));

-- name: ListZuechter :many
SELECT *
FROM PERSON
WHERE KZ = 'Z';

-- name: ListLieferanten :many
SELECT *
FROM PERSON
WHERE KZ = 'L';

-- name: GetCompanyPerson :one
SELECT *
FROM PERSON
WHERE KZ = 'F'
LIMIT 1;

-- name: GetGlobalFirmenparameter :one
SELECT *
FROM FIRMENPARAMETER
WHERE ID_HERDEN = -1
LIMIT 1;

-- name: GetFirmenparameterByHerde :one
SELECT *
FROM FIRMENPARAMETER
WHERE ID_HERDEN = $1 OR ID_HERDEN = -1
ORDER BY ID_HERDEN DESC
LIMIT 1;

-- name: CreatePerson :one
INSERT INTO PERSON (ID_TEXTE, ID_ANREDE, PERSONENNUMMER, KZ, POSTFACH, NAME, FIRMA, STRASSE, PLZ, ORT, TELEFON,
                    MOBILTELEPHON, EMAIL, EMAIL2, FOTO, HOMEPAGE)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING *;

-- name: UpdatePerson :one
UPDATE PERSON
SET ID_TEXTE = $1,
    ID_ANREDE      = $2,
    PERSONENNUMMER = $3,
    KZ             = $4,
    POSTFACH       = $5,
    NAME           = $6,
    FIRMA          = $7,
    STRASSE        = $8,
    PLZ            = $9,
    ORT            = $10,
    TELEFON        = $11,
    MOBILTELEPHON  = $12,
    EMAIL          = $13,
    EMAIL2         = $14,
    FOTO           = $15,
    HOMEPAGE       = $16
WHERE ID = $17 RETURNING *;

-- name: DeletePerson :exec
DELETE
FROM PERSON
WHERE ID = $1;

-- name: GetMwst :one
SELECT *
FROM MWST
WHERE ID = $1;

-- name: ListMwst :many
SELECT *
FROM MWST;

-- name: CreateMwst :one
INSERT INTO MWST (MWSTKZ, PROZENT, KONTO)
VALUES ($1, $2, $3) RETURNING *;

-- name: UpdateMwst :one
UPDATE MWST
SET MWSTKZ = $1, PROZENT = $2, KONTO = $3
WHERE ID = $4 RETURNING *;

-- name: DeleteMwst :exec
DELETE
FROM MWST
WHERE ID = $1;

-- name: GetRasse :one
SELECT *
FROM RASSE
WHERE ID = $1;

-- name: ListRassen :many
SELECT *
FROM RASSE;

-- name: CreateRasse :one
INSERT INTO RASSE (RASSE)
VALUES ($1) RETURNING *;

-- name: UpdateRasse :one
UPDATE RASSE
SET RASSE = $1
WHERE ID = $2 RETURNING *;

-- name: DeleteRasse :exec
DELETE
FROM RASSE
WHERE ID = $1;

-- name: GetStall :one
SELECT *
FROM STALL
WHERE ID = $1;

-- name: ListStaelle :many
SELECT *
FROM STALL;

-- name: CreateStall :one
INSERT INTO STALL (STALLNUMMER, BEZEICHNUNG) 
VALUES ($1, $2) RETURNING *;

-- name: UpdateStall :one
UPDATE STALL 
SET STALLNUMMER = $1, BEZEICHNUNG = $2
WHERE ID = $3 RETURNING *;

-- name: DeleteStall :exec
DELETE
FROM STALL
WHERE ID = $1;

-- name: CreateHerde :one
INSERT INTO HERDEN (HERDENNUMMER, BEZEICHNUNG, ID_RASSE, ID_ZUECHTER, ID_EILAGER, ANFANGSBESTAND, EINSTALLDATUM,
                    LEGEDATUM, EINSTALLKOSTEN, ID_SILO, ID_STALL, AKTIV, ALLEBUCHUNGENMITDATUM)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING *;

-- name: ListHerdenLookup :many
SELECT ID, HERDENNUMMER, COALESCE(BEZEICHNUNG, '') AS BEZEICHNUNG, 
       COALESCE(LEGEDATUM, '0001-01-01') AS LEGEDATUM, 
       ANFANGSBESTAND, ID_EILAGER, AKTIV
FROM HERDEN
ORDER BY HERDENNUMMER;

-- name: UpdateHerde :one
UPDATE HERDEN
SET HERDENNUMMER = $1,
    BEZEICHNUNG = $2,
    ID_RASSE = $3,
    ID_ZUECHTER = $4,
    ID_EILAGER = $5,
    ANFANGSBESTAND = $6,
    EINSTALLDATUM = $7,
    LEGEDATUM = $8,
    EINSTALLKOSTEN = $9,
    ID_SILO = $10,
    ID_STALL = $11,
    AKTIV = $12,
    ALLEBUCHUNGENMITDATUM = $13
WHERE ID = $14 RETURNING *;

-- name: UpdateHerdeStock :exec
UPDATE HERDEN
SET ANFANGSBESTAND = ANFANGSBESTAND - $1
WHERE ID = $2;

-- name: AdjustHerdeStock :exec
UPDATE HERDEN
SET ANFANGSBESTAND = ANFANGSBESTAND + $1
WHERE ID = $2;

-- name: IncreaseHerdeStockAndCosts :exec
UPDATE HERDEN
SET ANFANGSBESTAND = ANFANGSBESTAND + $1,
    EINSTALLKOSTEN = EINSTALLKOSTEN + $2
WHERE HERDENNUMMER = $3;

-- name: UpdateBuchungStock :exec
UPDATE BUCHUNG
SET TIERBESTAND = TIERBESTAND + $1
WHERE HERDENNUMMER = $2
  AND BUCHUNGSDATUM = $3;

-- name: UpdateBuchungStockById :exec
UPDATE BUCHUNG
SET TIERBESTAND = TIERBESTAND + $1
WHERE ID = $2;

-- name: IncreaseHerdeStockById :exec
UPDATE HERDEN
SET ANFANGSBESTAND = ANFANGSBESTAND + $1
WHERE ID = $2;

-- name: ListBuchungenWithHerde :many
SELECT B.ID,
       B.ID_HERDEN,
       B.HERDENNUMMER,
       B.BUCHUNGSDATUM,
       B.TIERBESTAND,
       H.BEZEICHNUNG AS HERDEN_BEZEICHNUNG
FROM BUCHUNG B
         JOIN HERDEN H ON B.ID_HERDEN = H.ID
ORDER BY B.BUCHUNGSDATUM DESC;

-- name: ListHerdenDetailed :many
SELECT H.ID, H.ID_SILO, H.ID_STALL, H.ID_EILAGER, H.ID_GEWICHTTAB, H.ID_ZUECHTER, H.ID_RASSE, 
       H.HERDENNUMMER, COALESCE(H.BEZEICHNUNG, '') AS BEZEICHNUNG, H.ANFANGSKOSTEN, H.ANFANGSBESTAND, 
       COALESCE(H.EINSTALLDATUM, '0001-01-01') AS EINSTALLDATUM, 
       COALESCE(H.LEGEDATUM, '0001-01-01') AS LEGEDATUM, 
       H.EINSTALLKOSTEN, 
       COALESCE(H.DATUM, '0001-01-01') AS DATUM, 
       H.AKTIV, H.AW, H.ALLEBUCHUNGENMITDATUM,
       COALESCE(E.BEZEICHNUNG, '') AS LAGERNAME,
       COALESCE(S.BEZEICHNUNG, '') AS STALL_BEZEICHNUNG,
       COALESCE(S.STALLNUMMER, 0)  AS STALLNUMMER
FROM HERDEN H
         LEFT JOIN EILAGER E ON H.ID_EILAGER = E.ID
         LEFT JOIN STALL S ON H.ID_STALL = S.ID;

-- name: CreateHerdeChecked :one
INSERT INTO HERDEN (
    HERDENNUMMER, BEZEICHNUNG, ID_RASSE, ID_ZUECHTER, ID_EILAGER, ANFANGSBESTAND,
    EINSTALLDATUM, LEGEDATUM, EINSTALLKOSTEN, ID_SILO, ID_STALL, AKTIV, ALLEBUCHUNGENMITDATUM
) 
SELECT SQLC.ARG(HERDENNUMMER),
       SQLC.ARG(BEZEICHNUNG),
       SQLC.ARG(ID_RASSE),
       SQLC.ARG(ID_ZUECHTER),
       SQLC.ARG(ID_EILAGER),
       SQLC.ARG(ANFANGSBESTAND),
       SQLC.ARG(EINSTALLDATUM),
       SQLC.ARG(LEGEDATUM),
       SQLC.ARG(EINSTALLKOSTEN),
       SQLC.ARG(ID_SILO),
       SQLC.ARG(ID_STALL),
       SQLC.ARG(AKTIV),
       SQLC.ARG(ALLEBUCHUNGENMITDATUM) WHERE EXISTS (SELECT 1 FROM EILAGER WHERE ID = SQLC.ARG(ID_EILAGER))
RETURNING ID, ID_SILO, ID_STALL, ID_EILAGER, ID_GEWICHTTAB, ID_ZUECHTER, ID_RASSE, HERDENNUMMER, BEZEICHNUNG, ANFANGSKOSTEN, ANFANGSBESTAND, EINSTALLDATUM, LEGEDATUM, EINSTALLKOSTEN, DATUM, AKTIV, AW, ALLEBUCHUNGENMITDATUM;

-- name: CreateSilo :one
INSERT INTO SILO (SILONUMMER, PERSONENNUMMER, BEZEICHNUNG, INVENTURDATUMALT, INVENTURDATUMNEU, MAXFUELLMENGE,
                  MINFUELLMENGE,
                  INVENTURFUELLMENGE, ID_LIEFERANT)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *;

-- name: UpdateSilo :one
UPDATE SILO 
SET SILONUMMER = $1,
    PERSONENNUMMER = $2,
    BEZEICHNUNG = $3,
    INVENTURDATUMALT = $4,
    INVENTURDATUMNEU = $5,
    MAXFUELLMENGE = $6,
    MINFUELLMENGE = $7,
    INVENTURFUELLMENGE = $8,
    ID_LIEFERANT   = $9
WHERE ID = $10 RETURNING *;

-- name: DeleteHerde :exec
DELETE
FROM HERDEN
WHERE ID = $1;

-- name: DeleteSilo :exec
DELETE
FROM SILO
WHERE ID = $1;

-- name: CreateFirmenparameter :one
INSERT INTO FIRMENPARAMETER (
    ID_HERDEN, KZ, JUMBOS, KLASSENERFASSEN, KLASSEAERFASSEN, KLASSEAERRECHNEN, KLASSEAVERMITTELN,
    ERFASSESCHMUTZEI, ERFASSEKNICKEI, ERFASSEBRUCHEI, ERFASSEVOLLEI, MASSVOLLEI,
    AUFTEILUNGGEWICHT, KONTROLLWIEGUNG, ANZAHLKONTROLLW, VERPACKUNGKG, AUFTEILUNGALTER,
    ERFASSEVOLLEIKG, LAUFZEITWOCHEN, ZEITSTEMPEL, SCHLACHTERLOESHENNE, PRODUKTIONSDAUER,
    ID_TABELLEGEWICHT, ID_TABELLEALTER, LEGEBEGINN_LW, VERLUSTEBEIBUCHUNG, LAGERBUCHUNGBEIBUCHUNG,
    MAXTAGEVERMITTELN, CHARGEJUMBOS, CHARGEXL, CHARGEMEDIUM, CHARGESMALL, CHARGELARGE, CHARGEVOLLEI,
    CHARGEPREFIXFIRMA, CHARGEPREFIXHERDENNUMMER, CHARGEDATUM, CHARGELAGERNUMMER, CHARGETRENNUNG,
    BEIVERMITTELNDATUMAKTUELL, PSEUDOLAGER, BIO, HALTUNGSTYP, BIOAUFSCHLAG, FUTTERINVENTUR)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37,
        $38, $39, $40, $41, $42, $43, $44, $45) RETURNING *;

-- name: UpdateFirmenparameter :one
UPDATE FIRMENPARAMETER
SET KZ = $1, JUMBOS = $2, KLASSENERFASSEN = $3, KLASSEAERFASSEN = $4, KLASSEAERRECHNEN = $5, KLASSEAVERMITTELN = $6,
    ERFASSESCHMUTZEI = $7, ERFASSEKNICKEI = $8, ERFASSEBRUCHEI = $9, ERFASSEVOLLEI = $10, MASSVOLLEI = $11,
    AUFTEILUNGGEWICHT = $12, KONTROLLWIEGUNG = $13, ANZAHLKONTROLLW = $14, VERPACKUNGKG = $15, AUFTEILUNGALTER = $16,
    ERFASSEVOLLEIKG = $17, LAUFZEITWOCHEN = $18, ZEITSTEMPEL = $19, SCHLACHTERLOESHENNE = $20, PRODUKTIONSDAUER = $21,
    ID_TABELLEGEWICHT         = $22,
    ID_TABELLEALTER           = $23,
    LEGEBEGINN_LW             = $24,
    VERLUSTEBEIBUCHUNG        = $25,
    LAGERBUCHUNGBEIBUCHUNG    = $26,
    MAXTAGEVERMITTELN         = $27,
    CHARGEJUMBOS              = $28,
    CHARGEXL                  = $29,
    CHARGEMEDIUM              = $30,
    CHARGESMALL               = $31,
    CHARGELARGE               = $32,
    CHARGEVOLLEI              = $33,
    CHARGEPREFIXFIRMA         = $34,
    CHARGEPREFIXHERDENNUMMER  = $35,
    CHARGEDATUM               = $36,
    CHARGELAGERNUMMER         = $37,
    CHARGETRENNUNG            = $38,
    BEIVERMITTELNDATUMAKTUELL = $39,
    PSEUDOLAGER  = $40,
    BIO          = $41,
    HALTUNGSTYP  = $42,
    BIOAUFSCHLAG = $43,
    FUTTERINVENTUR = $44
WHERE ID_HERDEN = $45 RETURNING *;

-- name: DeleteFirmenparameter :exec
DELETE
FROM FIRMENPARAMETER
WHERE ID_HERDEN = $1;

-- name: GetEggStatsByHerde :one
SELECT COALESCE(SUM(KLASSEA), 0)                                                               AS SUM_KLASSE_A,
       COALESCE(SUM(SMALL), 0)                                                                 AS SUM_SMALL,
       COALESCE(SUM(MEDIUM), 0)                                                                AS SUM_MEDIUM,
       COALESCE(SUM(LARGE), 0)                                                                 AS SUM_LARGE,
       COALESCE(SUM(XL), 0)                                                                    AS SUM_XL,
       COALESCE(SUM(VERLUSTE), 0) +
       COALESCE((SELECT SUM(T.BEWEGUNGEN)
                 FROM TIERBEWEGUNGEN T
                          JOIN HERDEN H ON T.HERDENNUMMER = H.HERDENNUMMER
                 WHERE H.ID = $1), 0) AS SUM_VERLUSTE
FROM BUCHUNG
WHERE BUCHUNG.ID_HERDEN = $2
  AND VERMITTELT IN ('N', 'V');

-- name: GetEggStatsByHerdeFiltered :one
SELECT COALESCE(SUM(KLASSEA), 0)  AS SUM_KLASSE_A,
       COALESCE(SUM(SMALL), 0)    AS SUM_SMALL,
       COALESCE(SUM(MEDIUM), 0)   AS SUM_MEDIUM,
       COALESCE(SUM(LARGE), 0)    AS SUM_LARGE,
       COALESCE(SUM(XL), 0)       AS SUM_XL,
       COALESCE(SUM(VERLUSTE), 0) AS SUM_VERLUSTE
FROM BUCHUNG
WHERE (sqlc.arg(id_herden) = -1 OR BUCHUNG.ID_HERDEN = sqlc.arg(id_herden))
  AND (sqlc.arg(only_active) = 0 OR EXISTS (SELECT 1 FROM HERDEN H WHERE H.ID = BUCHUNG.ID_HERDEN AND H.AKTIV = 1))
  AND (sqlc.arg(year) = '' OR strftime('%Y', BUCHUNGSDATUM) = sqlc.arg(year))
  AND (sqlc.arg(quarter) = 0 OR (CAST(strftime('%m', BUCHUNGSDATUM) AS INTEGER) + 2) / 3 = sqlc.arg(quarter))
  AND (sqlc.arg(month) = 0 OR CAST(strftime('%m', BUCHUNGSDATUM) AS INTEGER) = sqlc.arg(month))
  AND VERMITTELT IN ('N', 'V');

-- name: GetEggBookingYears :many
SELECT DISTINCT strftime('%Y', BUCHUNGSDATUM) as year
FROM BUCHUNG
WHERE (sqlc.arg(id_herden) = -1
   OR ID_HERDEN = sqlc.arg(id_herden))
  AND (sqlc.arg(only_active) = 0
   OR EXISTS (SELECT 1 FROM HERDEN H WHERE H.ID = BUCHUNG.ID_HERDEN
  AND H.AKTIV = 1))
ORDER BY year DESC;

-- name: GetEggStatsWeeklyByHerde :many
SELECT LW                         AS LEBENSWOCHE,
       MAX(BUCHUNGSDATUM)         AS LETZTES_DATUM,
       COALESCE(SUM(KLASSEA), 0)  AS SUM_KLASSE_A,
       COALESCE(SUM(SMALL), 0)    AS SUM_SMALL,
       COALESCE(SUM(MEDIUM), 0)   AS SUM_MEDIUM,
       COALESCE(SUM(LARGE), 0)    AS SUM_LARGE,
       COALESCE(SUM(XL), 0)       AS SUM_XL,
       COALESCE(SUM(VERLUSTE), 0) AS SUM_VERLUSTE
FROM BUCHUNG
WHERE ID_HERDEN = $1
  AND VERMITTELT IN ('N', 'V')
GROUP BY LW
ORDER BY LEBENSWOCHE DESC;

-- name: GetBuchung :one
SELECT *
FROM BUCHUNG
WHERE ID = $1;

-- name: ListBuchungen :many
SELECT B.ID,
       B.ID_HERDEN,
       B.LW,
       B.HERDENNUMMER,
       B.BUCHUNGSDATUM,
       B.GEWICHTPROBE,
       B.KONTROLLGEWICHT,
       B.KLASSEA,
       B.VERLUSTE,
       B.EIMASSE,
       B.SCHMUTZ,
       B.KNICKEIER,
       B.VOLLEI,
       B.BRUCHEIER,
       B.TIERBESTAND,
       B.ID_EITABELLE,
       B.ID_DGEWICHTTAB,
       B.FUTTERKTAG,
       B.SILONR,
       B.KL6,
       B.VERMITTELTAM,
       B.SMALL,
       B.LARGE,
       B.MEDIUM,
       B.XL,
       B.ZEITSTEMPEL,
       B.DGEWICHTEI,
       B.AW,
       B.VERMITTELT,
       B.FUTTERVERBRAUCHTIER,
       H.HERDENNUMMER AS HERDEN_NUMMER_REL,
       H.BEZEICHNUNG AS HERDEN_BEZEICHNUNG_REL,
       H.ID_EILAGER   AS HERDEN_ID_EILAGER,
       H.AKTIV        AS HERDEN_AKTIV_REL
FROM BUCHUNG B
         LEFT JOIN HERDEN H ON B.ID_HERDEN = H.ID
WHERE B.VERMITTELT != 'S'
ORDER BY B.BUCHUNGSDATUM DESC;

-- name: CreateBuchung :one
INSERT INTO BUCHUNG (
    ID_HERDEN, LW, HERDENNUMMER, BUCHUNGSDATUM, GEWICHTPROBE, KONTROLLGEWICHT,
    KLASSEA, VERLUSTE, EIMASSE, SCHMUTZ, KNICKEIER, VOLLEI, BRUCHEIER,
    TIERBESTAND, ID_EITABELLE, ID_DGEWICHTTAB, FUTTERKTAG, SILONR,
    KL6, VERMITTELTAM, SMALL, LARGE, MEDIUM, XL, DGEWICHTEI, ZEITSTEMPEL, AW, VERMITTELT, FUTTERVERBRAUCHTIER)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29)
RETURNING *;

-- name: UpdateBuchung :one
UPDATE BUCHUNG
SET ID_HERDEN = $1, LW = $2, HERDENNUMMER = $3, BUCHUNGSDATUM = $4, GEWICHTPROBE = $5,
    KONTROLLGEWICHT = $6, KLASSEA = $7, VERLUSTE = $8, EIMASSE = $9, SCHMUTZ = $10,
    KNICKEIER = $11, VOLLEI = $12, BRUCHEIER = $13, TIERBESTAND = $14, ID_EITABELLE = $15,
    ID_DGEWICHTTAB = $16, FUTTERKTAG = $17, SILONR = $18, KL6 = $19, VERMITTELTAM = $20,
    SMALL       = $21,
    LARGE       = $22,
    MEDIUM      = $23,
    XL          = $24,
    DGEWICHTEI  = $25,
    ZEITSTEMPEL = $26,
    AW          = $27,
    VERMITTELT  = $28,
    FUTTERVERBRAUCHTIER = $29
WHERE ID = $30 RETURNING *;

-- name: DeleteBuchung :exec
DELETE
FROM BUCHUNG
WHERE ID = $1;

-- name: GetLatestBookingByHerde :one
SELECT ID, BUCHUNGSDATUM, TIERBESTAND, VERLUSTE
FROM BUCHUNG
WHERE ID_HERDEN = $1
ORDER BY BUCHUNGSDATUM DESC
LIMIT 1;

-- name: ListFutterBuchungen :many
SELECT F.ID,
       F.ID_SILO,
       F.SILONUMMER,
       F.HERDENR,
       F.ID_PERSON,
       F.LIEFERDATUM,
       F.LIEFERMENGE,
       F.PREISDT,
       F.RABATTPROZ,
       F.NETTO,
       F.BRUTTO,
       F.MWSTPROZ,
       F.MWSTKZ,
       F.DATUM,
       F.ZEITSTEMPEL,
       F.AW,
       F.ID_FUTTERSORTEN,
       FS.BEZEICHNUNG AS FUTTERSORTE_TEXT
FROM FUTTER F
         LEFT JOIN FUTTERSORTEN FS ON F.ID_FUTTERSORTEN = FS.ID
ORDER BY F.LIEFERDATUM DESC;

-- name: CreateFutterBuchung :one
INSERT INTO FUTTER (ID_SILO, SILONUMMER, HERDENR, ID_PERSON, LIEFERDATUM,
    LIEFERMENGE, PREISDT, RABATTPROZ, NETTO, BRUTTO,
                    MWSTPROZ, MWSTKZ, DATUM, ZEITSTEMPEL, AW, ID_FUTTERSORTEN)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING *;

-- name: UpdateFutterBuchung :one
UPDATE FUTTER
SET ID_SILO     = $1,
    SILONUMMER  = $2,
    HERDENR     = $3,
    ID_PERSON   = $4,
    LIEFERDATUM = $5,
    LIEFERMENGE = $6, PREISDT = $7, RABATTPROZ = $8, NETTO = $9, BRUTTO = $10,
    MWSTPROZ    = $11,
    MWSTKZ      = $12,
    DATUM       = $13,
    ZEITSTEMPEL = $14,
    AW          = $15,
    ID_FUTTERSORTEN = $16
WHERE ID = $17 RETURNING *;

-- name: DeleteFutterBuchung :exec
DELETE
FROM FUTTER
WHERE ID = $1;

-- name: ListTierbewegungen :many
SELECT T.ID,
       COALESCE(T.HERDENNUMMER, 0)   AS HERDENNUMMER,
       COALESCE(T.ID_BUCHUNG, 0)     AS ID_BUCHUNG,
       COALESCE(T.TYP, 'x')          AS TYP,
       COALESCE(T.ID_TEXTE, 0)       AS ID_TEXTE,
       COALESCE(T.BEWEGUNGSDATUM, '0001-01-01') AS BEWEGUNGSDATUM,
       COALESCE(T.BEWEGUNGEN, 0)     AS BEWEGUNGEN,
       COALESCE(T.ID_HERDEN_VON, 0)  AS ID_HERDEN_VON,
       COALESCE(T.ID_HERDEN_NACH, 0) AS ID_HERDEN_NACH,
       COALESCE(T.KOSTEN, 0)         AS KOSTEN,
       TXT.TEXT_TYP_KZ,
       U.BETREFF      AS GRUND_TEXT,
       H.BEZEICHNUNG  AS HERDEN_BEZEICHNUNG,
       HV.BEZEICHNUNG                AS HERDEN_VON_BEZEICHNUNG,
       HN.BEZEICHNUNG                AS HERDEN_NACH_BEZEICHNUNG
FROM TIERBEWEGUNGEN T
         LEFT JOIN TEXTE TXT ON T.ID_TEXTE = TXT.ID
         LEFT JOIN UEBERSETZUNGEN U ON TXT.ID = U.ID_TEXTE AND U.SPRACHE_KZ = $1
         LEFT JOIN HERDEN H ON T.HERDENNUMMER = H.HERDENNUMMER
         LEFT JOIN HERDEN HV ON T.ID_HERDEN_VON = HV.ID
         LEFT JOIN HERDEN HN ON T.ID_HERDEN_NACH = HN.ID
ORDER BY T.BEWEGUNGSDATUM DESC;

-- name: CreateTierbewegung :one
INSERT INTO TIERBEWEGUNGEN (HERDENNUMMER, ID_BUCHUNG, TYP, ID_TEXTE,
                            BEWEGUNGSDATUM, BEWEGUNGEN, ID_HERDEN_VON, ID_HERDEN_NACH, KOSTEN)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *;

-- name: UpdateTierbewegung :one
UPDATE TIERBEWEGUNGEN
SET HERDENNUMMER   = $1,
    ID_BUCHUNG     = $2,
    TYP            = $3,
    ID_TEXTE       = $4,
    BEWEGUNGSDATUM = $5,
    BEWEGUNGEN     = $6,
    ID_HERDEN_VON  = $7,
    ID_HERDEN_NACH = $8,
    KOSTEN         = $9
WHERE ID = $10 RETURNING *;

-- name: DeleteTierbewegung :exec
DELETE
FROM TIERBEWEGUNGEN
WHERE ID = $1;

-- name: GetKostentabkopf :one
SELECT *
FROM KOSTENTABKOPF
WHERE ID = 1;

-- name: UpdateKostentabkopf :one
INSERT INTO KOSTENTABKOPF (ID, SCHLACHTERLOES, PRODDAUERGEPLANT, GEBAEUDEWERT, ABSCHREIBUNG_G, GERAETEWERT,
                           ABSCHREIBUNG_R, KOSTENTAG)
VALUES (1, $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(ID) DO UPDATE SET
    SCHLACHTERLOES = EXCLUDED.SCHLACHTERLOES,
                       PRODDAUERGEPLANT = EXCLUDED.PRODDAUERGEPLANT,
                       GEBAEUDEWERT = EXCLUDED.GEBAEUDEWERT,
                       ABSCHREIBUNG_G = EXCLUDED.ABSCHREIBUNG_G,
                       GERAETEWERT = EXCLUDED.GERAETEWERT,
                       ABSCHREIBUNG_R = EXCLUDED.ABSCHREIBUNG_R,
                       KOSTENTAG = EXCLUDED.KOSTENTAG
RETURNING *;

-- name: ListKosten :many
SELECT *
FROM KOSTEN
WHERE ID_KOSTENTABKOPF = 1
ORDER BY BUCHUNGSDATUM DESC;

-- name: CreateKosten :one
INSERT INTO KOSTEN (
    ID_KOSTENTABKOPF, KOSTENTYP, BEZEICHNUNG, KOSTEN, TAGE, BUCHUNGSDATUM
) VALUES (1, $1, $2, $3, $4, $5)
RETURNING *;

-- name: UpdateKosten :one
UPDATE KOSTEN
SET KOSTENTYP = $1, BEZEICHNUNG = $2, KOSTEN = $3, TAGE = $4, BUCHUNGSDATUM = $5
WHERE ID = $6
RETURNING *;

-- name: DeleteKosten :exec
DELETE
FROM KOSTEN
WHERE ID = $1;

-- name: ListTextTypen :many
SELECT ID, KZ, BEZEICHNUNG, SYSTEM_KZ, STATUS
FROM TEXT_TYPEN;

-- name: CreateTextTyp :one
INSERT INTO TEXT_TYPEN (KZ, BEZEICHNUNG, SYSTEM_KZ, STATUS)
VALUES ($1, $2, $3, $4) RETURNING *;

-- name: UpdateTextTyp :one
UPDATE TEXT_TYPEN
SET KZ          = $1,
    BEZEICHNUNG = $2,
    SYSTEM_KZ    = $3,
    STATUS      = $4
WHERE ID = $5 RETURNING *;

-- name: DeleteTextTyp :exec
DELETE
FROM TEXT_TYPEN
WHERE ID = $1;

-- name: ListTexte :many
SELECT T.ID,
       T.TEXT_TYP_KZ,
       T.KZ,
       T.SYSTEM_KZ, T.STATUS,
       
       COALESCE(U.BETREFF, '') AS BETREFF,
       COALESCE(U.INHALT, '')  AS INHALT
FROM TEXTE T
         LEFT JOIN UEBERSETZUNGEN U ON T.ID = U.ID_TEXTE AND U.SPRACHE_KZ = $1;

-- name: CreateText :one
INSERT INTO TEXTE (TEXT_TYP_KZ, KZ, SYSTEM_KZ, STATUS)
VALUES ($1, $2, $3, $4) RETURNING *;

-- name: UpdateText :one
UPDATE TEXTE
SET TEXT_TYP_KZ = $1,
    KZ          = $2,
    SYSTEM_KZ    = $3,
    STATUS      = $4
WHERE ID = $5 RETURNING *;

-- name: DeleteText :exec
DELETE
FROM TEXTE
WHERE ID = $1;

-- name: ListTexteByType :many
SELECT T.ID,
       T.TEXT_TYP_KZ,
       T.KZ,
       T.SYSTEM_KZ, T.STATUS,
       COALESCE(U.BETREFF, '') AS BETREFF,
       COALESCE(U.INHALT, '')  AS INHALT
FROM TEXTE T
         LEFT JOIN UEBERSETZUNGEN U ON T.ID = U.ID_TEXTE AND U.SPRACHE_KZ = $1
WHERE T.TEXT_TYP_KZ = $2;

-- name: ListVerwendungsTexte :many
SELECT T.ID,
       T.KZ,
       T.TEXT_TYP_KZ,
       T.SYSTEM_KZ, T.STATUS,
       U.BETREFF
FROM TEXTE T
         INNER JOIN UEBERSETZUNGEN U ON T.ID = U.ID_TEXTE
WHERE T.TEXT_TYP_KZ = 'E'
  AND T.KZ <> 'E'
  AND U.SPRACHE_KZ = $1;

-- name: ListTexteByKZ :many
SELECT T.ID,
       T.TEXT_TYP_KZ,
       T.KZ,
       T.SYSTEM_KZ, T.STATUS,
       COALESCE(U.BETREFF, '') AS BETREFF,
       COALESCE(U.INHALT, '')  AS INHALT
FROM TEXTE T
         LEFT JOIN UEBERSETZUNGEN U ON T.ID = U.ID_TEXTE AND U.SPRACHE_KZ = $1
WHERE T.KZ = $2;

-- name: CreateUebersetzung :one
INSERT INTO UEBERSETZUNGEN (ID_TEXTE, SPRACHE_KZ, BETREFF, INHALT)
VALUES ($1, $2, $3, $4) RETURNING *;

-- name: UpdateUebersetzung :one
UPDATE UEBERSETZUNGEN
SET BETREFF = $1,
    INHALT  = $2
WHERE ID_TEXTE = $3
  AND SPRACHE_KZ = $4
RETURNING *;

-- name: UpsertUebersetzung :one
INSERT INTO UEBERSETZUNGEN (ID_TEXTE, SPRACHE_KZ, BETREFF, INHALT)
VALUES ($1, $2, $3, $4) ON CONFLICT(ID_TEXTE, SPRACHE_KZ) DO
UPDATE SET
    BETREFF = EXCLUDED.BETREFF,
    INHALT = EXCLUDED.INHALT
RETURNING *;

-- name: GetTranslatedText :one
SELECT T.ID,
       T.TEXT_TYP_KZ,
       T.SYSTEM_KZ, T.STATUS,
       COALESCE(U_TARGET.BETREFF, U_DEFAULT.BETREFF, '')         AS BETREFF,
       COALESCE(U_TARGET.INHALT, U_DEFAULT.INHALT, '')           AS INHALT,
       COALESCE(U_TARGET.SPRACHE_KZ, U_DEFAULT.SPRACHE_KZ, 'DE') AS SPRACHE_KZ
FROM TEXTE T
         LEFT JOIN UEBERSETZUNGEN U_TARGET ON T.ID = U_TARGET.ID_TEXTE AND U_TARGET.SPRACHE_KZ = $1
         LEFT JOIN UEBERSETZUNGEN U_DEFAULT ON T.ID = U_DEFAULT.ID_TEXTE AND U_DEFAULT.SPRACHE_KZ = 'DE'
WHERE T.ID = $2;

-- name: ListSolltabellen :many
SELECT ID, BEZEICHNUNG
FROM TABELLENKOPF
WHERE TABELLENTYP = 'S'
ORDER BY BEZEICHNUNG;

-- name: ListTabellenkopfByType :many
SELECT ID,
       TABELLENTYP,
       TABELLENNUMMER,
       BEZEICHNUNG,
       COALESCE(ANLAGEDATUM, '0001-01-01') AS ANLAGEDATUM,
       COALESCE(DATUM, '0001-01-01')       AS DATUM
FROM TABELLENKOPF
WHERE TRIM(TABELLENTYP) = $1
ORDER BY BEZEICHNUNG;

-- name: UpdateTabellenkopf :one
UPDATE TABELLENKOPF
SET TABELLENNUMMER = $1,
    BEZEICHNUNG    = $2,
    ANLAGEDATUM    = $3,
    DATUM          = $4
WHERE ID = $5 RETURNING *;

-- name: CreateTabellenkopf :one
INSERT INTO TABELLENKOPF (TABELLENTYP, TABELLENNUMMER, BEZEICHNUNG, ANLAGEDATUM, DATUM)
VALUES ($1, $2, $3, $4, $5) RETURNING *;

-- name: ListLSLKlassikByTabNum :many
SELECT *
FROM LSLKLASSIK
WHERE TABELLENNUMMER = $1
ORDER BY ALTERINWOCHEN;

-- name: ListGewichtByTabNum :many
SELECT *
FROM GEWICHTTABELLE
WHERE TABELLENNUMMER = $1
ORDER BY EIGEWICHT;

-- name: CreateLSLKlassik :one
INSERT INTO LSLKLASSIK (TABELLENNUMMER, ALTERINWOCHEN, EIZAHLKUM, LEGERATEAH, LEGERATEDH, EIGEWICHTWO, EIGEWICHTKUM,
                        EIMASSEWO, EIMASSEKUM)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *;

-- name: UpdateLSLKlassik :one
UPDATE LSLKLASSIK
SET TABELLENNUMMER = $1,
    ALTERINWOCHEN  = $2,
    EIZAHLKUM      = $3,
    LEGERATEAH     = $4,
    LEGERATEDH     = $5,
    EIGEWICHTWO    = $6,
    EIGEWICHTKUM   = $7,
    EIMASSEWO      = $8,
    EIMASSEKUM     = $9
WHERE ID = $10 RETURNING *;

-- name: DeleteLSLKlassik :exec
DELETE
FROM LSLKLASSIK
WHERE ID = $1;

-- name: CreateGewichtTabelle :one
INSERT INTO GEWICHTTABELLE (TABELLENNUMMER, EIGEWICHT, KLASSE1, KLASSE2, KLASSE3, KLASSE4, KLASSE5, KLASSE6, KLASSE7)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *;

-- name: UpdateGewichtTabelle :one
UPDATE GEWICHTTABELLE
SET TABELLENNUMMER = $1,
    EIGEWICHT      = $2,
    KLASSE1        = $3,
    KLASSE2        = $4,
    KLASSE3        = $5,
    KLASSE4        = $6,
    KLASSE5        = $7,
    KLASSE6        = $8,
    KLASSE7        = $9
WHERE ID = $10 RETURNING *;

-- name: DeleteGewichtTabelle :exec
DELETE
FROM GEWICHTTABELLE
WHERE ID = $1;

-- name: GetTabellenkopf :one
SELECT ID,
       TABELLENTYP,
       TABELLENNUMMER,
       BEZEICHNUNG,
       COALESCE(ANLAGEDATUM, '0001-01-01') AS ANLAGEDATUM,
       COALESCE(DATUM, '0001-01-01')       AS DATUM
FROM TABELLENKOPF
WHERE ID = $1;

-- name: GetGewichtByTabNumAndWeight :one
SELECT *
FROM GEWICHTTABELLE
WHERE TABELLENNUMMER = $1
  AND ROUND(EIGEWICHT, 1) = ROUND($2, 1)
LIMIT 1;

-- name: GetLSLByTabNumAndAge :one
SELECT *
FROM LSLKLASSIK
WHERE TABELLENNUMMER = $1 AND ALTERINWOCHEN = $2
LIMIT 1;

-- name: AddEilagerBuchung :one
INSERT INTO EILAGERBUCHUNG (ID_FREMDESLAGER, ID_BUCHUNG, ID_EILAGER, BUCHUNGSDATUM, JUMBOS, XL, LARGE, MEDIUM, SMALL,
                            VOLLEIKG, SCHMUTZ, KNICKEIER, BRUCHEIER, BUCHUNGSTYP, CHARGE, KZ_LAGER, ID_FREMDEBUCHUNG,
                            VERKAUF)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING *;

-- name: UpdateEilagerBuchung :one
UPDATE EILAGERBUCHUNG
SET
  ID_FREMDESLAGER = $1,
  ID_BUCHUNG = $2,
  ID_EILAGER = $3,
  BUCHUNGSDATUM = $4,
  JUMBOS = $5,
  XL = $6,
  LARGE = $7,
  MEDIUM = $8,
  SMALL = $9,
  VOLLEIKG = $10,
  SCHMUTZ = $11,
  KNICKEIER = $12,
  BRUCHEIER = $13,
  BUCHUNGSTYP = $14,
  CHARGE   = $15,
  KZ_LAGER         = $16,
  ID_FREMDEBUCHUNG = $17,
  VERKAUF          = $18
WHERE ID = $19 RETURNING *;

-- name: GetEilagerBuchung :one
SELECT *
FROM EILAGERBUCHUNG
WHERE ID = $1;

-- name: DeleteEilagerBuchung :exec
DELETE FROM EILAGERBUCHUNG
WHERE ID = $1;

-- name: ListEilagerBuchungenByLager :many
SELECT *
FROM EILAGERBUCHUNG
WHERE ID_EILAGER = sqlc.arg(lager_id)
ORDER BY BUCHUNGSDATUM DESC;

-- name: GetBuchungGroupTotals :one
SELECT SUM(KL6)    AS JUMBOS,
       SUM(XL)     AS XL,
       SUM(LARGE)  AS LARGE,
       SUM(MEDIUM) AS MEDIUM,
       SUM(SMALL)  AS SMALL,
       SUM(VOLLEI) AS VOLLEIKG
FROM BUCHUNG
WHERE ID_HERDEN = $1
  AND VERMITTELTAM = $2
  AND VERMITTELT IN ('V', 'S');

-- name: GetEilagerGroupTotals :one
SELECT SUM(JUMBOS)   AS JUMBOS,
       SUM(XL)       AS XL,
       SUM(LARGE)    AS LARGE,
       SUM(MEDIUM)   AS MEDIUM,
       SUM(SMALL)    AS SMALL,
       SUM(VOLLEIKG) AS VOLLEIKG
FROM EILAGERBUCHUNG
WHERE ID_BUCHUNG IN (SELECT ID
                     FROM BUCHUNG
                     WHERE ID_HERDEN = $1
                       AND VERMITTELTAM = $2
                       AND VERMITTELT IN ('V', 'S'))
  AND (ID_FREMDESLAGER IS NULL OR ID_FREMDESLAGER = 0);

-- name: GetEilagerSumByBuchungID :one
SELECT CAST(COALESCE(SUM(JUMBOS), 0) AS INTEGER)   AS JUMBOS,
       CAST(COALESCE(SUM(XL), 0) AS INTEGER)       AS XL,
       CAST(COALESCE(SUM(LARGE), 0) AS INTEGER)    AS LARGE,
       CAST(COALESCE(SUM(MEDIUM), 0) AS INTEGER)   AS MEDIUM,
       CAST(COALESCE(SUM(SMALL), 0) AS INTEGER)    AS SMALL,
       CAST(COALESCE(SUM(VOLLEIKG), 0) AS DECIMAL) AS VOLLEIKG,
       CAST(COALESCE(SUM(SCHMUTZ), 0) AS INTEGER)   AS SCHMUTZ,
       CAST(COALESCE(SUM(KNICKEIER), 0) AS INTEGER) AS KNICKEIER,
       CAST(COALESCE(SUM(BRUCHEIER), 0) AS INTEGER) AS BRUCHEIER
FROM EILAGERBUCHUNG
WHERE ID_BUCHUNG = $1
  AND (ID_FREMDESLAGER IS NULL OR ID_FREMDESLAGER = 0);

-- name: GetEilagerSumBySource :one
SELECT CAST(COALESCE(SUM(JUMBOS), 0) AS INTEGER)   AS JUMBOS,
       CAST(COALESCE(SUM(XL), 0) AS INTEGER)       AS XL,
       CAST(COALESCE(SUM(LARGE), 0) AS INTEGER)    AS LARGE,
       CAST(COALESCE(SUM(MEDIUM), 0) AS INTEGER)   AS MEDIUM,
       CAST(COALESCE(SUM(SMALL), 0) AS INTEGER)    AS SMALL,
       CAST(COALESCE(SUM(VOLLEIKG), 0) AS DECIMAL) AS VOLLEIKG
FROM EILAGERBUCHUNG
WHERE ID_BUCHUNG = $1
  AND ID_FREMDESLAGER = $2;

-- name: ListEilagerBuchungenByKZ :many
SELECT EB.*
FROM EILAGERBUCHUNG EB
         LEFT JOIN EILAGER E1 ON EB.ID_EILAGER = E1.ID
WHERE E1.KZ = sqlc.arg(kz)
ORDER BY EB.BUCHUNGSDATUM DESC;

-- name: GetEilager :one
SELECT *
FROM EILAGER
WHERE ID = $1;

-- name: CreateEilager :one
INSERT INTO EILAGER (LAGERNUMMER, KZ, BEZEICHNUNG, LETZTE_BUCHUNG, JUMBOS, XL, LARGE, MEDIUM, SMALL, VOLLEIKG, AW)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING *;

-- name: UpdateEilager :one
UPDATE EILAGER
SET LAGERNUMMER    = $1,
  KZ = $2,
  BEZEICHNUNG = $3,
    LETZTE_BUCHUNG = $4,
    JUMBOS         = $5,
  XL = $6,
  LARGE = $7,
    MEDIUM         = $8,
  SMALL = $9,
  VOLLEIKG = $10,
  AW = $11
WHERE ID = $12
RETURNING *;

-- name: DeleteEilager :exec
DELETE
FROM EILAGER
WHERE ID = $1;

-- name: ListLagerplaetze :many
SELECT LP.ID, LP.ID_EILAGER, LP.BEZEICHNUNG, LP.BEMERKUNG, E.BEZEICHNUNG AS EILAGER_BEZEICHNUNG
FROM LAGERPLATZ LP
         JOIN EILAGER E ON LP.ID_EILAGER = E.ID
ORDER BY LP.BEZEICHNUNG;

-- name: ListLagerplaetzeByEilager :many
SELECT LP.ID, LP.ID_EILAGER, LP.BEZEICHNUNG, LP.BEMERKUNG, E.BEZEICHNUNG AS EILAGER_BEZEICHNUNG
FROM LAGERPLATZ LP
         JOIN EILAGER E ON LP.ID_EILAGER = E.ID
WHERE LP.ID_EILAGER = $1
ORDER BY LP.BEZEICHNUNG;

-- name: GetLagerplatz :one
SELECT * FROM LAGERPLATZ WHERE ID = $1;

-- name: CreateLagerplatz :one
INSERT INTO LAGERPLATZ (ID_EILAGER, BEZEICHNUNG, BEMERKUNG)
VALUES ($1, $2, $3) RETURNING *;

-- name: UpdateLagerplatz :one
UPDATE LAGERPLATZ
SET ID_EILAGER = $1, BEZEICHNUNG = $2, BEMERKUNG = $3
WHERE ID = $4 RETURNING *;

-- name: DeleteLagerplatz :exec
DELETE FROM LAGERPLATZ WHERE ID = $1;

-- name: GetBestandsuebersicht :many
SELECT CHARGE,
       LAGERPLATZ_BEZEICHNUNG,
       LAGERPLATZ_ID,
       EILAGER_KZ,
       EILAGER_ID,
       EILAGER_BEZEICHNUNG,
       SUM(JUMBOS)   AS JUMBOS,
       SUM(XL)       AS XL,
       SUM(LARGE)    AS LARGE,
       SUM(MEDIUM)   AS MEDIUM,
       SUM(SMALL)    AS SMALL,
       SUM(VOLLEIKG) AS VOLLEIKG
FROM (
         -- Positive Buchungen (Einlagerung / Ziel einer Umbuchung)
         SELECT EB.CHARGE,
                LP.BEZEICHNUNG AS LAGERPLATZ_BEZEICHNUNG,
                LP.ID          AS LAGERPLATZ_ID,
                E.KZ           AS EILAGER_KZ,
                EB.ID_EILAGER  AS EILAGER_ID,
                E.BEZEICHNUNG  AS EILAGER_BEZEICHNUNG,
                EB.JUMBOS,
                EB.XL,
                EB.LARGE,
                EB.MEDIUM,
                EB.SMALL,
                EB.VOLLEIKG
         FROM EILAGERBUCHUNG EB
                  LEFT JOIN EILAGER E ON EB.ID_EILAGER = E.ID
                  LEFT JOIN LAGERPLATZ LP ON EB.ID_LAGERPLATZ = LP.ID
         WHERE ($1 = 0 OR EB.ID_EILAGER = $2)

         UNION ALL

         -- Negative Buchungen (Abgang / Quelle einer Umbuchung)
         SELECT EB.CHARGE,
                ''                 AS LAGERPLATZ_BEZEICHNUNG,
                0                  AS LAGERPLATZ_ID,
                E.KZ               AS EILAGER_KZ,
                EB.ID_FREMDESLAGER AS EILAGER_ID,
                E.BEZEICHNUNG      AS EILAGER_BEZEICHNUNG,
                -EB.JUMBOS,
                -EB.XL,
                -EB.LARGE,
                -EB.MEDIUM,
                -EB.SMALL,
                -EB.VOLLEIKG
         FROM EILAGERBUCHUNG EB
                  LEFT JOIN EILAGER E ON EB.ID_FREMDESLAGER = E.ID
         WHERE EB.ID_FREMDESLAGER != 0 AND ($3 = 0 OR EB.ID_FREMDESLAGER = $4))
GROUP BY CHARGE, LAGERPLATZ_ID, EILAGER_ID, EILAGER_KZ, EILAGER_BEZEICHNUNG
ORDER BY EILAGER_BEZEICHNUNG, CHARGE, LAGERPLATZ_BEZEICHNUNG;

-- name: ListEierpreise :many
SELECT *
FROM EIERPREISE
ORDER BY KZ_HALTUNGSTYP, GEWICHT_VON DESC;

-- name: GetEierpreis :one
SELECT *
FROM EIERPREISE
WHERE ID = $1;

-- name: CreateEierpreis :one
INSERT INTO EIERPREISE (KZ_HALTUNGSTYP, EIERKLASSE, GEWICHT_VON, GEWICHT_BIS, PREIS_VON, PREIS_BIS)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING *;

-- name: UpdateEierpreis :one
UPDATE EIERPREISE
SET KZ_HALTUNGSTYP = $1,
    EIERKLASSE     = $2,
    GEWICHT_VON    = $3,
    GEWICHT_BIS    = $4,
    PREIS_VON      = $5,
    PREIS_BIS      = $6
WHERE ID = $7 RETURNING *;

-- name: DeleteEierpreis :exec
DELETE
FROM EIERPREISE
WHERE ID = $1;

-- name: ListDynamischeSQL :many
SELECT ID,
       BESCHREIBUNG,
       SQLSTATEMENT,
       KATEGORIE_KZ,
       GRUPPEN_KZ,
       TYP_KZ,
       SYSTEM_KZ,
       TEMPLATE_NAME,
       PARAM_DEF,
       DETAIL_SQL,
       LINK_LOGIC,
       GROUP_FIELD,
       ROWS_PER_PAGE,
       PAGE_ORIENTATION,
       SHOW_MASTER_GRID,
       SHOW_DETAIL_GRID,
       SQLSTATEMENT_NATIVE,
       DETAIL_SQL_NATIVE,
       ROOT_KZ,
       SUMMENZEILE,
       IST_SUMMENZEILE
FROM DYNAMISCHE_SQL
ORDER BY ROOT_KZ ASC,
         GRUPPEN_KZ ASC,
         CASE WHEN KATEGORIE_KZ = 'K' THEN 0 WHEN KATEGORIE_KZ = 'L' THEN 1 ELSE 2 END ASC,
         BESCHREIBUNG ASC;


-- name: GetDynamischeSQL :one
SELECT *
FROM DYNAMISCHE_SQL
WHERE ID = $1;

-- name: CreateDynamischeSQL :one
INSERT INTO DYNAMISCHE_SQL (BESCHREIBUNG, SQLSTATEMENT, KATEGORIE_KZ, GRUPPEN_KZ, TYP_KZ, TEMPLATE_NAME, PARAM_DEF,
                            DETAIL_SQL, LINK_LOGIC, GROUP_FIELD, ROWS_PER_PAGE, PAGE_ORIENTATION, SHOW_MASTER_GRID,
                            SHOW_DETAIL_GRID, SYSTEM_KZ,
                            SQLSTATEMENT_NATIVE, DETAIL_SQL_NATIVE, ROOT_KZ, SUMMENZEILE, IST_SUMMENZEILE)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) RETURNING *;
-- name: UpdateDynamischeSQL :one
UPDATE DYNAMISCHE_SQL
SET BESCHREIBUNG = $1,
    SQLSTATEMENT = $2,
    KATEGORIE_KZ  = $3,
    GRUPPEN_KZ    = $4,
    TYP_KZ        = $5,
    TEMPLATE_NAME = $6,
    PARAM_DEF    = $7,
    DETAIL_SQL   = $8,
    LINK_LOGIC   = $9,
    GROUP_FIELD         = $10,
    ROWS_PER_PAGE       = $11,
    PAGE_ORIENTATION    = $12,
    SHOW_MASTER_GRID    = $13,
    SHOW_DETAIL_GRID    = $14,
    SYSTEM_KZ           = $15,
    SQLSTATEMENT_NATIVE = $16,
    DETAIL_SQL_NATIVE = $17,
    ROOT_KZ         = $18,
    SUMMENZEILE     = $19,
    IST_SUMMENZEILE = $20
WHERE ID = $21 RETURNING *;
-- name: DeleteDynamischeSQL :exec
DELETE
FROM DYNAMISCHE_SQL
WHERE ID = $1;

-- name: ListTranslateFeldnamen :many
SELECT COALESCE(BETREFF, '') AS BETREFF, COALESCE(INHALT, '') AS INHALT
FROM TRANSLATEFELDNAMEN
WHERE SPRACHE_KZ = $1;

-- name: ListFieldTranslations :many
SELECT F.ID,
       F.KZ,
       F.FELDNAME,
       F.NAMEINDB,
       COALESCE(T.INHALT, '')  AS INHALT,
       COALESCE(T.BETREFF, '') AS BETREFF
FROM FELD_KATALOG F
         LEFT JOIN TRANSLATEFELDNAMEN T ON F.ID = T.ID_FELD_KATALOG AND T.SPRACHE_KZ = $1
ORDER BY F.FELDNAME;

-- name: UpsertFieldTranslation :one
INSERT INTO TRANSLATEFELDNAMEN (ID_FELD_KATALOG, SPRACHE_KZ, BETREFF, INHALT)
VALUES ($1, $2, $3, $4) ON CONFLICT(ID_FELD_KATALOG, SPRACHE_KZ) DO
UPDATE SET
    BETREFF = EXCLUDED.BETREFF,
    INHALT = EXCLUDED.INHALT
    RETURNING *;

-- name: CreateFieldKatalog :one
INSERT INTO FELD_KATALOG (KZ, FELDNAME, NAMEINDB)
VALUES ($1, $2, $3) RETURNING *;

-- name: DeleteFieldKatalog :exec
DELETE
FROM FELD_KATALOG
WHERE ID = $1;

-- name: GetBenutzerProfilByID :one
SELECT *
FROM BENUTZERPROFILE
WHERE ID = $1 LIMIT 1;

-- name: DeleteBenutzerProfil :exec
DELETE
FROM BENUTZERPROFILE
WHERE PROFIL_KZ = $1;


-- name: GetBenutzerProfilByKZ :one
SELECT *
FROM BENUTZERPROFILE
WHERE PROFIL_KZ = $1;

-- name: ListBenutzerProfile :many
SELECT *
FROM BENUTZERPROFILE;

-- name: CreateBenutzerProfil :one
INSERT INTO BENUTZERPROFILE (PROFIL_KZ, BESCHREIBUNG, F_DASHBOARD, F_HERDEN_VERWALTEN, F_EINRICHTUNGEN_VERWALTEN,
                             F_PERSONEN_VERWALTEN, F_BUCHUNGEN_ERFASSEN, F_AUSWERTUNGEN_ANZEIGEN,
                             F_SQL_STRUKTUR_VERWALTEN, F_BENUTZER_PROFILE, F_PARAMETER_EDITIEREN, F_KOSTEN_VERWALTEN,
                             F_TABELLEN_ANZEIGEN, F_TEXTE_VERWALTEN, F_SYSTEM_VERWALTUNG, F_BACKUP_ERSTELLEN)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING *;


-- name: UpdateBenutzerProfil :one
UPDATE BENUTZERPROFILE
SET BESCHREIBUNG              = $1,
    F_DASHBOARD               = $2,
    F_HERDEN_VERWALTEN        = $3,
    F_EINRICHTUNGEN_VERWALTEN = $4,
    F_PERSONEN_VERWALTEN      = $5,
    F_BUCHUNGEN_ERFASSEN      = $6,
    F_AUSWERTUNGEN_ANZEIGEN   = $7,
    F_SQL_STRUKTUR_VERWALTEN  = $8,
    F_BENUTZER_PROFILE        = $9,
    F_PARAMETER_EDITIEREN     = $10,
    F_KOSTEN_VERWALTEN        = $11,
    F_TABELLEN_ANZEIGEN       = $12,
    F_TEXTE_VERWALTEN         = $13,
    F_SYSTEM_VERWALTUNG       = $14,
    F_BACKUP_ERSTELLEN        = $15
WHERE PROFIL_KZ = $16 RETURNING *;


-- name: GetBenutzerByUsername :one
SELECT *
FROM BENUTZER
WHERE USERNAME = $1;

-- name: ListBenutzer :many
SELECT B.*, P.PROFIL_KZ
FROM BENUTZER B
         LEFT JOIN BENUTZERPROFILE P ON B.ID_BENUTZER_PROFILE = P.ID;

-- name: CreateBenutzer :one
INSERT INTO BENUTZER (USERNAME, PASSWORT, ID_BENUTZER_PROFILE, KLARNAME)
VALUES ($1, $2, $3, $4) RETURNING *;

-- name: UpdateBenutzer :exec
UPDATE BENUTZER
SET PASSWORT            = $1,
    ID_BENUTZER_PROFILE = $2,
    KLARNAME            = $3
WHERE ID = $4;

-- name: DeleteBenutzer :exec
DELETE
FROM BENUTZER
WHERE ID = $1;


-- name: ListShowTV :many
SELECT *
FROM SHOWTV;

-- name: GetShowTV :one
SELECT *
FROM SHOWTV
WHERE ID = $1;

-- name: CreateShowTV :one
INSERT INTO SHOWTV (TVNAME, SHOWIT)
VALUES ($1, $2) RETURNING *;

-- name: UpdateShowTV :one
UPDATE SHOWTV
SET TVNAME = $1,
    SHOWIT = $2
WHERE ID = $3 RETURNING *;

-- name: DeleteShowTV :exec
DELETE
FROM SHOWTV
WHERE ID = $1;

-- name: ListFuttersorten :many
SELECT *
FROM FUTTERSORTEN
ORDER BY BEZEICHNUNG;

-- name: CreateFuttersorte :one
INSERT INTO FUTTERSORTEN (BEZEICHNUNG)
VALUES ($1) RETURNING *;

-- name: UpdateFuttersorte :one
UPDATE FUTTERSORTEN
SET BEZEICHNUNG = $1
WHERE ID = $2 RETURNING *;

-- name: DeleteFuttersorte :exec
DELETE
FROM FUTTERSORTEN
WHERE ID = $1;

-- name: ListVerkauf :many
SELECT *
FROM VERKAUF
ORDER BY BUCHUNGSDATUM DESC;

-- name: GetVerkauf :one
SELECT *
FROM VERKAUF
WHERE ID = $1;

-- name: GetVerkaufByEilagerbuchung :one
SELECT *
FROM VERKAUF
WHERE ID_EILAGERBUCHUNG = $1;

-- name: CreateVerkauf :one
INSERT INTO VERKAUF (ID_EILAGERBUCHUNG, ID_BUCHUNG, BUCHUNGSDATUM,
                     MENGESMALL, MENGEMEDIUM, MENGELARGE, MENGEXL,
                     PREISSMALL, PREISMEDIUM, PREISLARGE, PREISXL,
                     GESAMTPREIS, BIO, VERBUCHT, CHARGE, RABATTPROZENT)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING *;

-- name: UpdateVerkauf :one
UPDATE VERKAUF
SET ID_EILAGERBUCHUNG = $1,
    ID_BUCHUNG        = $2,
    BUCHUNGSDATUM     = $3,
    MENGESMALL        = $4,
    MENGEMEDIUM       = $5,
    MENGELARGE        = $6,
    MENGEXL           = $7,
    PREISSMALL        = $8,
    PREISMEDIUM       = $9,
    PREISLARGE        = $10,
    PREISXL           = $11,
    GESAMTPREIS       = $12,
    BIO               = $13,
    VERBUCHT      = $14,
    CHARGE        = $15,
    RABATTPROZENT = $16
WHERE ID = $17 RETURNING *;

-- name: DeleteVerkauf :exec
DELETE
FROM VERKAUF
WHERE ID = $1;

-- name: DeleteVerkaufByEilagerbuchung :exec
DELETE
FROM VERKAUF
WHERE ID_EILAGERBUCHUNG = $1;

-- name: GetAktion :one
SELECT *
FROM AKTIONEN
WHERE ID = $1;

-- name: ListAktionen :many
SELECT a.id, a.aktionen_kz, a.id_user, a.aktionsdatum, a.bezeichnung, a.intervall_tage, a.anzahl_intervalle, a.erledigt, a.id_user_erledigt, a.erledigt_am, a.bemerkung,
       u1.USERNAME as username,
       u2.USERNAME as username_erledigt
FROM AKTIONEN a
LEFT JOIN BENUTZER u1 ON a.ID_USER = u1.ID
LEFT JOIN BENUTZER u2 ON a.ID_USER_ERLEDIGT = u2.ID
WHERE (sqlc.arg(id_user) = 0 OR a.ID_USER = sqlc.arg(id_user) OR a.ID_USER = 0)
  AND (sqlc.arg(start_date) = '' OR a.AKTIONSDATUM >= sqlc.arg(start_date))
  AND (sqlc.arg(end_date) = '' OR a.AKTIONSDATUM <= sqlc.arg(end_date))
  AND (sqlc.arg(kz) = '' OR a.AKTIONEN_KZ = sqlc.arg(kz))
  AND (sqlc.arg(status) = 2 OR COALESCE(a.ERLEDIGT, 0) = sqlc.arg(status))
ORDER BY a.AKTIONSDATUM DESC;

-- name: CreateAktion :one
INSERT INTO AKTIONEN (AKTIONEN_KZ, ID_USER, AKTIONSDATUM, BEZEICHNUNG, INTERVALL_TAGE, ANZAHL_INTERVALLE, ERLEDIGT, ID_USER_ERLEDIGT, ERLEDIGT_AM, BEMERKUNG)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING *;

-- name: UpdateAktion :one
UPDATE AKTIONEN
SET AKTIONEN_KZ       = $1,
    ID_USER           = $2,
    AKTIONSDATUM      = $3,
    BEZEICHNUNG       = $4,
    INTERVALL_TAGE    = $5,
    ANZAHL_INTERVALLE = $6,
    ERLEDIGT          = $7,
    ID_USER_ERLEDIGT  = $8,
    ERLEDIGT_AM       = $9,
    BEMERKUNG         = $10
WHERE ID = $11 RETURNING *;

-- name: DeleteAktion :exec
DELETE
FROM AKTIONEN
WHERE ID = $1;
