CREATE TABLE BUCHUNG
(
    ID              INTEGER        NOT NULL,
    ID_HERDEN       INTEGER        NOT NULL,
    LW              INTEGER        NOT NULL DEFAULT 0,
    HERDENNUMMER    INTEGER        NOT NULL DEFAULT 0,
    BUCHUNGSDATUM   VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    GEWICHTPROBE    INTEGER        NOT NULL DEFAULT 0,
    KONTROLLGEWICHT REAL           NOT NULL DEFAULT 0,
    KLASSEA         INTEGER        NOT NULL DEFAULT 0,
    VERLUSTE        INTEGER        NOT NULL DEFAULT 0,
    EIMASSE         REAL           NOT NULL DEFAULT 0,
    SCHMUTZ         INTEGER        NOT NULL DEFAULT 0,
    KNICKEIER       INTEGER        NOT NULL DEFAULT 0,
    VOLLEI          REAL           NOT NULL DEFAULT 0,
    BRUCHEIER       INTEGER        NOT NULL DEFAULT 0,
    TIERBESTAND     INTEGER        NOT NULL DEFAULT 0,
    ID_EITABELLE    INTEGER        NOT NULL DEFAULT 0,
    ID_DGEWICHTTAB  INTEGER        NOT NULL DEFAULT 0,
    FUTTERKTAG      INTEGER        NOT NULL DEFAULT 0,
    SILONR          INTEGER        NOT NULL DEFAULT 0,
    KL6             INTEGER        NOT NULL DEFAULT 0,
    VERMITTELTAM    VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    SMALL           INTEGER        NOT NULL DEFAULT 0,
    LARGE           INTEGER        NOT NULL DEFAULT 0,
    MEDIUM          INTEGER        NOT NULL DEFAULT 0,
    XL              INTEGER        NOT NULL DEFAULT 0,
    ZEITSTEMPEL     VARCHAR(50)    NOT NULL DEFAULT '',
    DGEWICHTEI      DECIMAL(10, 2) NOT NULL DEFAULT 0,
    AW              INTEGER        NOT NULL DEFAULT 0,
    VERMITTELT      CHAR(1)        NOT NULL DEFAULT 'x',
PRIMARY KEY (ID)
);
CREATE TABLE EILAGER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LAGERNUMMER    INTEGER     NOT NULL UNIQUE,
  KZ             CHAR(1)     NOT NULL DEFAULT 'x',
  BEZEICHNUNG    VARCHAR(30) NOT NULL DEFAULT '',
  LETZTE_BUCHUNG VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
  JUMBOS         INTEGER (15) NOT NULL DEFAULT 0,
  XL             INTEGER (15) NOT NULL DEFAULT 0,
  LARGE          INTEGER (15) NOT NULL DEFAULT 0,
  MEDIUM         INTEGER (15) NOT NULL DEFAULT 0,
  SMALL          INTEGER (15) NOT NULL DEFAULT 0,
  VOLLEIKG DECIMAL(10, 2) NOT NULL DEFAULT 0,
  KLASSE6        VARCHAR(20) NOT NULL DEFAULT '',
  KLASSE7        VARCHAR(20) NOT NULL DEFAULT '',
  AW             INTEGER     NOT NULL DEFAULT 0
);

CREATE TABLE EILAGERBUCHUNG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_FREMDESLAGER INTEGER      NOT NULL DEFAULT 0,
  ID_BUCHUNG      INTEGER      NOT NULL DEFAULT 0,
  ID_EILAGER      INTEGER      NOT NULL DEFAULT 0,
  BUCHUNGSDATUM   TEXT         NOT NULL DEFAULT '0001-01-01',
  JUMBOS          INTEGER      NOT NULL DEFAULT 0,
  XL              INTEGER      NOT NULL DEFAULT 0,
  LARGE           INTEGER      NOT NULL DEFAULT 0,
  MEDIUM          INTEGER      NOT NULL DEFAULT 0,
  SMALL           INTEGER      NOT NULL DEFAULT 0,
  VOLLEIKG         REAL    NOT NULL DEFAULT 0,
  SCHMUTZ         INTEGER      NOT NULL DEFAULT 0,
  KNICKEIER       INTEGER      NOT NULL DEFAULT 0,
  BRUCHEIER       INTEGER      NOT NULL DEFAULT 0,
  BUCHUNGSTYP     TEXT         NOT NULL DEFAULT 'E',
  CHARGE          VARCHAR(255) NOT NULL DEFAULT '',
  KZ_LAGER         TEXT    NOT NULL DEFAULT 'x',
  ID_FREMDEBUCHUNG INTEGER NOT NULL DEFAULT 0,
  VERKAUF          INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE FIRMENPARAMETER
(
    ID                        INTEGER        NOT NULL,
    ID_HERDEN                 INTEGER        NOT NULL DEFAULT 0,
    KZ                        CHAR(1)        NOT NULL DEFAULT 'x',
    JUMBOS                    INTEGER        NOT NULL DEFAULT 0,
    KLASSENERFASSEN           INTEGER        NOT NULL DEFAULT 0,
    KLASSEAERFASSEN           INTEGER        NOT NULL DEFAULT 0,
    KLASSEAERRECHNEN          INTEGER        NOT NULL DEFAULT 0,
    KLASSEAVERMITTELN         INTEGER        NOT NULL DEFAULT 0,
    ERFASSESCHMUTZEI          INTEGER        NOT NULL DEFAULT 0,
    ERFASSEKNICKEI            INTEGER        NOT NULL DEFAULT 0,
    ERFASSEBRUCHEI            INTEGER        NOT NULL DEFAULT 0,
    ERFASSEVOLLEI             INTEGER        NOT NULL DEFAULT 0,
    MASSVOLLEI                INTEGER        NOT NULL DEFAULT 0,
    AUFTEILUNGGEWICHT         INTEGER        NOT NULL DEFAULT 0,
    KONTROLLWIEGUNG           INTEGER        NOT NULL DEFAULT 0,
    ANZAHLKONTROLLW           INTEGER        NOT NULL DEFAULT 0,
    VERPACKUNGKG        REAL NOT NULL DEFAULT 0,
    AUFTEILUNGALTER           INTEGER        NOT NULL DEFAULT 0,
    ERFASSEVOLLEIKG           INTEGER        NOT NULL DEFAULT 0,
    LAUFZEITWOCHEN            INTEGER        NOT NULL DEFAULT 0,
    ZEITSTEMPEL               VARCHAR(50)    NOT NULL DEFAULT '',
    SCHLACHTERLOESHENNE REAL NOT NULL DEFAULT 0,
    PRODUKTIONSDAUER          INTEGER        NOT NULL DEFAULT 0,
    ID_TABELLEGEWICHT         INTEGER        NOT NULL DEFAULT 0,
    ID_TABELLEALTER           INTEGER        NOT NULL DEFAULT 0,
    LEGEBEGINN_LW             INTEGER        NOT NULL DEFAULT 18,
    VERLUSTEBEIBUCHUNG        INTEGER        NOT NULL DEFAULT 0,
    LAGERBUCHUNGBEIBUCHUNG    INTEGER        NOT NULL DEFAULT 0,
    AW                        INTEGER        NOT NULL DEFAULT 0,
    MAXTAGEVERMITTELN         INTEGER        NOT NULL DEFAULT 0,
    CHARGEJUMBOS             INTEGER NOT NULL DEFAULT 0,
    CHARGEXL                  INTEGER        NOT NULL DEFAULT 0,
    CHARGEMEDIUM              INTEGER        NOT NULL DEFAULT 0,
    CHARGESMALL               INTEGER        NOT NULL DEFAULT 0,
    CHARGELARGE               INTEGER        NOT NULL DEFAULT 0,
    CHARGEVOLLEI             INTEGER NOT NULL DEFAULT 0,
    CHARGEPREFIXFIRMA         TEXT(10) NOT NULL DEFAULT '',
    CHARGEPREFIXHERDENNUMMER INTEGER NOT NULL DEFAULT 0,
    CHARGEDATUM               INTEGER        NOT NULL DEFAULT 0,
    CHARGELAGERNUMMER         INTEGER        NOT NULL DEFAULT 0,
    CHARGETRENNUNG            CHAR(1)        NOT NULL DEFAULT '-',
    BEIVERMITTELNDATUMAKTUELL INTEGER        NOT NULL DEFAULT 0,
    PSEUDOLAGER               INTEGER        NOT NULL DEFAULT 0,
    BIO                       INTEGER        NOT NULL DEFAULT 0,
    HALTUNGSTYP               CHAR(1)        NOT NULL DEFAULT '3',
    BIOAUFSCHLAG              NUMERIC(3, 2)  NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE FUTTER
(
    ID              INTEGER        NOT NULL,
    ID_SILO         INTEGER        NOT NULL,
    SILONUMMER      INTEGER        NOT NULL DEFAULT 0,
    HERDENR         INTEGER        NOT NULL DEFAULT 0,
    ID_PERSON INTEGER NOT NULL DEFAULT 0,
    LIEFERDATUM     VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    LIEFERMENGE DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PREISDT         DECIMAL(18, 2) NOT NULL DEFAULT 0,
    RABATTPROZ      DECIMAL(10, 2) NOT NULL DEFAULT 0,
    NETTO           DECIMAL(18, 2) NOT NULL DEFAULT 0,
    BRUTTO          DECIMAL(18, 2) NOT NULL DEFAULT 0,
    MWSTPROZ        DECIMAL(6, 2)  NOT NULL DEFAULT 0,
    MWSTKZ          CHAR(1)        NOT NULL DEFAULT 'x',
    DATUM           VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    ZEITSTEMPEL     VARCHAR(50)    NOT NULL DEFAULT '',
    ID_FUTTERSORTEN INTEGER NOT NULL DEFAULT 0,
    AW              INTEGER        NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE HERDEN
(
    ID                    INTEGER        NOT NULL,
    ID_SILO               INTEGER        NOT NULL DEFAULT 0,
    ID_STALL              INTEGER        NOT NULL DEFAULT 0,
    ID_EILAGER            INTEGER        NOT NULL DEFAULT 0,
    ID_GEWICHTTAB         INTEGER        NOT NULL DEFAULT 0,
    ID_ZUECHTER           INTEGER        NOT NULL DEFAULT 0,
    ID_RASSE              INTEGER        NOT NULL DEFAULT 0,
    HERDENNUMMER          INTEGER UNIQUE NOT NULL DEFAULT 0,
    BEZEICHNUNG           TEXT           NOT NULL DEFAULT '',
    ANFANGSKOSTEN         INTEGER        NOT NULL DEFAULT 0,
    ANFANGSBESTAND        INTEGER        NOT NULL DEFAULT 0,
    EINSTALLDATUM         VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    LEGEDATUM             VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    EINSTALLKOSTEN        DECIMAL(10, 2) NOT NULL DEFAULT 0,
    DATUM                 VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    ZEITSTEMPEL           VARCHAR(50)    NOT NULL DEFAULT '',
    AKTIV                 INTEGER        NOT NULL DEFAULT 1,
    AW                    INTEGER        NOT NULL DEFAULT 0,
    ALLEBUCHUNGENMITDATUM INTEGER        NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE KLASSIFIZIERUNG
(
    ID          INTEGER       NOT NULL,
    PREIS       DECIMAL(8, 2) NOT NULL DEFAULT 0,
    KLASSE      VARCHAR(10)   NOT NULL DEFAULT '',
    VON         INTEGER       NOT NULL DEFAULT 0,
    BIS         INTEGER       NOT NULL DEFAULT 0,
    BEMERKUNG   VARCHAR(45)   NOT NULL DEFAULT '',
    ZEITSTEMPEL VARCHAR(50)   NOT NULL DEFAULT '',
    AW          INTEGER       NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE KOSTEN
(
    ID               INTEGER        NOT NULL,
    ID_KOSTENTABKOPF INTEGER        NOT NULL DEFAULT 1,
    KOSTENTYP        CHAR(1)        NOT NULL DEFAULT 'x',
    BEZEICHNUNG      VARCHAR(25)    NOT NULL DEFAULT '',
    KOSTEN           DECIMAL(12, 2) NOT NULL DEFAULT 0,
    TAGE             INTEGER        NOT NULL DEFAULT 0,
    BUCHUNGSDATUM    VARCHAR(25)    NOT NULL DEFAULT '0001-01-01',
    AW               INTEGER        NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE KOSTENTABKOPF
(
    ID               INTEGER        NOT NULL,
    SCHLACHTERLOES   DECIMAL(8, 2)  NOT NULL DEFAULT 0,
    PRODDAUERGEPLANT INTEGER        NOT NULL DEFAULT 0,
    GEBAEUDEWERT     DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ABSCHREIBUNG_G   DECIMAL(10, 2) NOT NULL DEFAULT 0,
    GERAETEWERT      DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ABSCHREIBUNG_R   DECIMAL(10, 2) NOT NULL DEFAULT 0,
    KOSTENTAG        DECIMAL(10, 2) NOT NULL DEFAULT 0,
    AW               INTEGER        NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE LSLKLASSIK
(
    ID             INTEGER        NOT NULL,
    TABELLENNUMMER INTEGER        NOT NULL DEFAULT 0,
    ALTERINWOCHEN  INTEGER        NOT NULL DEFAULT 0,
    EIZAHLKUM      DECIMAL(9, 2)  NOT NULL DEFAULT 0,
    LEGERATEAH     DECIMAL(8, 2)  NOT NULL DEFAULT 0,
    LEGERATEDH     DECIMAL(8, 2)  NOT NULL DEFAULT 0,
    EIGEWICHTWO    DECIMAL(8, 2)  NOT NULL DEFAULT 0,
    EIGEWICHTKUM   DECIMAL(8, 2)  NOT NULL DEFAULT 0,
    EIMASSEWO      DECIMAL(8, 2)  NOT NULL DEFAULT 0,
    EIMASSEKUM     DECIMAL(10, 2) NOT NULL DEFAULT 0,
    AW             INTEGER        NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE MWST
(
    ID      INTEGER       NOT NULL,
    MWSTKZ  CHAR(1)       NOT NULL DEFAULT 'x',
    PROZENT DECIMAL(8, 2) NOT NULL DEFAULT 0,
    KONTO   VARCHAR(8)    NOT NULL DEFAULT '',
    AW      INTEGER       NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE PERSON
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_TEXTE INTEGER NOT NULL DEFAULT 0,
    ID_ANREDE      INTEGER NOT NULL DEFAULT 0,
    PERSONENNUMMER INTEGER NOT NULL DEFAULT 0,
    POSTFACH       TEXT    NOT NULL DEFAULT '',
    NAME           TEXT    NOT NULL DEFAULT '',
    FIRMA          TEXT    NOT NULL DEFAULT '',
    STRASSE        TEXT    NOT NULL DEFAULT '',
    PLZ            TEXT    NOT NULL DEFAULT '',
    ORT            TEXT    NOT NULL DEFAULT '',
    TELEFON        TEXT    NOT NULL DEFAULT '',
    MOBILTELEPHON  TEXT    NOT NULL DEFAULT '',
    EMAIL          TEXT    NOT NULL DEFAULT '',
    EMAIL2         TEXT    NOT NULL DEFAULT '',
    FOTO     BLOB,
    KZ             TEXT    NOT NULL DEFAULT 'x',
    HOMEPAGE       TEXT    NOT NULL DEFAULT ''
);
CREATE TABLE RASSE
(
    ID    INTEGER     NOT NULL,
    RASSE VARCHAR(20) NOT NULL DEFAULT '',
    AW    INTEGER     NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);
CREATE TABLE SILO
(
    ID                 INTEGER PRIMARY KEY AUTOINCREMENT,
    SILONUMMER         INTEGER     NOT NULL DEFAULT 0,
    PERSONENNUMMER INTEGER NOT NULL DEFAULT 0,
    ID_LIEFERANT       INTEGER     NOT NULL DEFAULT 0,
    BEZEICHNUNG        VARCHAR(30) NOT NULL DEFAULT '',
    INVENTURDATUMALT   VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    INVENTURDATUMNEU   VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    MAXFUELLMENGE      INTEGER     NOT NULL DEFAULT 0,
    MINFUELLMENGE      INTEGER     NOT NULL DEFAULT 0,
    INVENTURFUELLMENGE INTEGER     NOT NULL DEFAULT 0,
    AW                 INTEGER     NOT NULL DEFAULT 0
);
CREATE TABLE STALL
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ALT      INTEGER NOT NULL DEFAULT 0,
    STALLNUMMER INTEGER NOT NULL DEFAULT 0,
    BEZEICHNUNG TEXT    NOT NULL DEFAULT ''
);
CREATE TABLE TABELLENKOPF
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TABELLENTYP    CHAR(1)     NOT NULL,
    TABELLENNUMMER INTEGER     NOT NULL,
    BEZEICHNUNG    VARCHAR(40) NOT NULL DEFAULT '',
    ANLAGEDATUM    VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    DATUM          VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
	UNIQUE (TABELLENTYP, TABELLENNUMMER)
);
CREATE TABLE TEXT_TYPEN
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    KZ          TEXT UNIQUE NOT NULL DEFAULT 'x',
    BEZEICHNUNG TEXT        NOT NULL DEFAULT '',
    SYSTEM      INTEGER     NOT NULL DEFAULT 0
);
CREATE TABLE TEXTE
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    TEXT_TYP_KZ TEXT    NOT NULL DEFAULT '',
    KZ          CHAR(1) NOT NULL DEFAULT 'x',
    SYSTEM      INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (TEXT_TYP_KZ) REFERENCES TEXT_TYPEN (KZ)
);
CREATE TABLE UEBERSETZUNGEN
(
    ID_TEXTE INTEGER NOT NULL,
    SPRACHE_KZ TEXT    NOT NULL,
    BETREFF    TEXT    NOT NULL DEFAULT '',
    INHALT     TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (ID_TEXTE, SPRACHE_KZ),
    FOREIGN KEY (ID_TEXTE) REFERENCES TEXTE (ID) ON DELETE CASCADE
);
CREATE TABLE TIERBEWEGUNGEN
(
    ID             INTEGER PRIMARY KEY AUTOINCREMENT,
    HERDENNUMMER   INTEGER DEFAULT (0),
    ID_BUCHUNG     INTEGER DEFAULT (0),
    TYP            CHAR(1) DEFAULT 'x',
    ID_TEXTE       INTEGER DEFAULT (0),
    BEWEGUNGSDATUM TEXT    DEFAULT ('0001-01-01'),
    BEWEGUNGEN     INTEGER DEFAULT (0),
    ID_HERDEN_VON  INTEGER DEFAULT (0),
    ID_HERDEN_NACH INTEGER DEFAULT (0),
    KOSTEN         NUMERIC DEFAULT (0)
);
CREATE TABLE VERLUSTE
(
    ID             INTEGER     NOT NULL,
    ID_HERDEN      INTEGER     NOT NULL DEFAULT 0,
    VERLUSTE       INTEGER     NOT NULL DEFAULT 0,
    HERDENNUMMER   INTEGER     NOT NULL DEFAULT 0,
    TYP            CHAR(1)     NOT NULL DEFAULT 'x',
    GRUND          INTEGER     NOT NULL DEFAULT 0,
    BEWEGUNGSDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    AW             INTEGER     NOT NULL DEFAULT 0,
PRIMARY KEY (ID)
);

CREATE TABLE GEWICHTTABELLE
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TABELLENNUMMER INTEGER       NOT NULL DEFAULT 0,
    EIGEWICHT      DECIMAL(5, 2) NOT NULL DEFAULT 0,
    KLASSE1        DECIMAL(5, 2) NOT NULL DEFAULT 0,
    KLASSE2        DECIMAL(5, 2) NOT NULL DEFAULT 0,
    KLASSE3        DECIMAL(5, 2) NOT NULL DEFAULT 0,
    KLASSE4        DECIMAL(5, 2) NOT NULL DEFAULT 0,
    KLASSE5        DECIMAL(5, 2) NOT NULL DEFAULT 0,
    KLASSE6        DECIMAL(5, 2) NOT NULL DEFAULT 0,
    KLASSE7        DECIMAL(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE LAGERPLATZ (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EILAGER  INTEGER NOT NULL DEFAULT 0,
  BEZEICHNUNG TEXT(40) NOT NULL DEFAULT '',
  BEMERKUNG   TEXT    NOT NULL DEFAULT '',
  FOREIGN KEY (ID_EILAGER) REFERENCES EILAGER(ID)
);

CREATE TABLE EIERPREISE
(
    ID             INTEGER PRIMARY KEY AUTOINCREMENT,
    KZ_HALTUNGSTYP CHAR(1)       NOT NULL DEFAULT 'x',
    EIERKLASSE     TEXT          NOT NULL DEFAULT '',
    GEWICHT_VON    NUMERIC(5, 2) NOT NULL DEFAULT 0,
    GEWICHT_BIS    NUMERIC(5, 2) NOT NULL DEFAULT 0,
    PREIS_VON      NUMERIC(5, 2) NOT NULL DEFAULT 0,
    PREIS_BIS      NUMERIC(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE DYNAMISCHE_SQL
(
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    BESCHREIBUNG TEXT NOT NULL,
    SQLSTATEMENT  TEXT NOT NULL,
    KATEGORIE_KZ  CHAR(1) NOT NULL DEFAULT 'x',
    GRUPPEN_KZ    CHAR(1) NOT NULL DEFAULT 'x',
    TYP_KZ        CHAR(1) NOT NULL DEFAULT 'x',
    TEMPLATE_NAME TEXT    NOT NULL DEFAULT '',
    PARAM_DEF     TEXT    NOT NULL DEFAULT '',
    DETAIL_SQL          TEXT    NOT NULL DEFAULT '',
    LINK_LOGIC          TEXT    NOT NULL DEFAULT '', -- JSON logic for linking Master and Detail
    GROUP_FIELD         TEXT    NOT NULL DEFAULT '',
    ROWS_PER_PAGE       INTEGER NOT NULL DEFAULT 0,
    PAGE_ORIENTATION    TEXT    NOT NULL DEFAULT 'P',
    SHOW_MASTER_GRID    INTEGER NOT NULL DEFAULT 0,
    SHOW_DETAIL_GRID    INTEGER NOT NULL DEFAULT 0,
    SYSTEM_KZ   TEXT NOT NULL DEFAULT '0',
    SQLSTATEMENT_NATIVE TEXT    NOT NULL DEFAULT '',
    DETAIL_SQL_NATIVE TEXT    NOT NULL DEFAULT '',
    ROOT_KZ           CHAR(1) NOT NULL DEFAULT 'x',
    SUMMENZEILE TEXT NOT NULL DEFAULT '',
    IST_SUMMENZEILE   INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE TRANSLATEFELDNAMEN
(
    ID_FELD_KATALOG INTEGER NOT NULL,
    SPRACHE_KZ      TEXT    NOT NULL,
    BETREFF         TEXT    NOT NULL DEFAULT '',
    INHALT          TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (ID_FELD_KATALOG, SPRACHE_KZ)
);

CREATE TABLE FELD_KATALOG
(
    ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    KZ       TEXT NOT NULL DEFAULT 'x',
    FELDNAME TEXT    NOT NULL DEFAULT '',
    NAMEINDB INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS BENUTZERPROFILE
(
    ID
    INTEGER
    PRIMARY
    KEY
    AUTOINCREMENT,
    PROFIL_KZ
    CHAR
(
    1
) NOT NULL UNIQUE,
    BESCHREIBUNG TEXT NOT NULL DEFAULT '',
    F_DASHBOARD INTEGER NOT NULL DEFAULT 0,
    F_HERDEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_EINRICHTUNGEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_PERSONEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_BUCHUNGEN_ERFASSEN INTEGER NOT NULL DEFAULT 0,
    F_AUSWERTUNGEN_ANZEIGEN INTEGER NOT NULL DEFAULT 0,
    F_SQL_STRUKTUR_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_BENUTZER_PROFILE INTEGER NOT NULL DEFAULT 0,
    F_PARAMETER_EDITIEREN INTEGER NOT NULL DEFAULT 0,
    F_KOSTEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_TABELLEN_ANZEIGEN INTEGER NOT NULL DEFAULT 0,
    F_TEXTE_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_SYSTEM_VERWALTUNG INTEGER NOT NULL DEFAULT 0,
    F_BACKUP_ERSTELLEN INTEGER NOT NULL DEFAULT 0
    );

CREATE TABLE BENUTZER
(
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME            TEXT    NOT NULL UNIQUE,
    PASSWORT            TEXT    NOT NULL,
    KLARNAME            TEXT    NOT NULL DEFAULT '',
    ID_BENUTZER_PROFILE INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_BENUTZER_PROFILE) REFERENCES BENUTZERPROFILE (ID)
);

CREATE TABLE SHOWTV
(
    ID     INTEGER PRIMARY KEY AUTOINCREMENT,
    TVNAME TEXT(30) NOT NULL DEFAULT '',
    SHOWIT INTEGER NOT NULL DEFAULT 0
);



CREATE TABLE FUTTERSORTEN
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    BEZEICHNUNG TEXT NOT NULL DEFAULT 'x'
);

CREATE TABLE VERKAUF
(
    ID                INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_EILAGERBUCHUNG INTEGER NOT NULL DEFAULT 0 UNIQUE,
    ID_BUCHUNG        INTEGER NOT NULL DEFAULT 0,
    BUCHUNGSDATUM     TEXT    NOT NULL DEFAULT '0001-01-01',
    MENGESMALL        INTEGER NOT NULL DEFAULT 0 CHECK (MENGESMALL >= 0),
    MENGEMEDIUM       INTEGER NOT NULL DEFAULT 0 CHECK (MENGEMEDIUM >= 0),
    MENGELARGE        INTEGER NOT NULL DEFAULT 0 CHECK (MENGELARGE >= 0),
    MENGEXL           INTEGER NOT NULL DEFAULT 0 CHECK (MENGEXL >= 0),
    PREISSMALL        REAL    NOT NULL DEFAULT 0.0 CHECK (PREISSMALL >= 0),
    PREISMEDIUM       REAL    NOT NULL DEFAULT 0.0 CHECK (PREISMEDIUM >= 0),
    PREISLARGE        REAL    NOT NULL DEFAULT 0.0 CHECK (PREISLARGE >= 0),
    PREISXL           REAL    NOT NULL DEFAULT 0.0 CHECK (PREISXL >= 0),
    GESAMTPREIS       REAL    NOT NULL DEFAULT 0.0 CHECK (GESAMTPREIS >= 0),
    BIO               BOOLEAN NOT NULL DEFAULT 0,
    VERBUCHT          BOOLEAN NOT NULL DEFAULT 0,
    CHARGE        TEXT(25) NOT NULL DEFAULT '',
    RABATTPROZENT NUMERIC(5, 2) NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_EILAGERBUCHUNG) REFERENCES EILAGERBUCHUNG (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_lagerbuchung ON EILAGERBUCHUNG (ID_BUCHUNG, ID_EILAGER, BUCHUNGSDATUM, KZ_LAGER);
