CREATE TABLE BUCHUNG (
    ID SERIAL PRIMARY KEY,
    ID_HERDEN INTEGER NOT NULL,
    LW INTEGER NOT NULL DEFAULT 0,
    HERDENNUMMER INTEGER NOT NULL DEFAULT 0,
    BUCHUNGSDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    GEWICHTPROBE INTEGER NOT NULL DEFAULT 0,
    KONTROLLGEWICHT DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSEA INTEGER NOT NULL DEFAULT 0,
    VERLUSTE INTEGER NOT NULL DEFAULT 0,
    EIMASSE DOUBLE PRECISION NOT NULL DEFAULT 0,
    SCHMUTZ INTEGER NOT NULL DEFAULT 0,
    KNICKEIER INTEGER NOT NULL DEFAULT 0,
    VOLLEI DOUBLE PRECISION NOT NULL DEFAULT 0,
    BRUCHEIER INTEGER NOT NULL DEFAULT 0,
    TIERBESTAND INTEGER NOT NULL DEFAULT 0,
    ID_EITABELLE INTEGER NOT NULL DEFAULT 0,
    ID_DGEWICHTTAB INTEGER NOT NULL DEFAULT 0,
    FUTTERKTAG INTEGER NOT NULL DEFAULT 0,
    SILONR INTEGER NOT NULL DEFAULT 0,
    KL6 INTEGER NOT NULL DEFAULT 0,
    VERMITTELTAM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    SMALL INTEGER NOT NULL DEFAULT 0,
    LARGE INTEGER NOT NULL DEFAULT 0,
    MEDIUM INTEGER NOT NULL DEFAULT 0,
    XL INTEGER NOT NULL DEFAULT 0,
    ZEITSTEMPEL VARCHAR(50) NOT NULL DEFAULT '',
    DGEWICHTEI DOUBLE PRECISION NOT NULL DEFAULT 0,
    AW INTEGER NOT NULL DEFAULT 0,
    VERMITTELT CHAR(1) NOT NULL DEFAULT 'x',
    FUTTERVERBRAUCHTIER INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE EILAGER (
    ID SERIAL PRIMARY KEY,
    LAGERNUMMER INTEGER NOT NULL UNIQUE,
    KZ CHAR(1) NOT NULL DEFAULT 'x',
    BEZEICHNUNG VARCHAR(30) NOT NULL DEFAULT '',
    LETZTE_BUCHUNG VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    JUMBOS INTEGER NOT NULL DEFAULT 0,
    XL INTEGER NOT NULL DEFAULT 0,
    LARGE INTEGER NOT NULL DEFAULT 0,
    MEDIUM INTEGER NOT NULL DEFAULT 0,
    SMALL INTEGER NOT NULL DEFAULT 0,
    VOLLEIKG DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE6 VARCHAR(20) NOT NULL DEFAULT '',
    KLASSE7 VARCHAR(20) NOT NULL DEFAULT '',
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE EILAGERBUCHUNG (
    ID SERIAL PRIMARY KEY,
    ID_FREMDESLAGER INTEGER NOT NULL DEFAULT 0,
    ID_BUCHUNG INTEGER NOT NULL DEFAULT 0,
    ID_EILAGER INTEGER NOT NULL DEFAULT 0,
    BUCHUNGSDATUM VARCHAR(191) NOT NULL DEFAULT '0001-01-01',
    JUMBOS INTEGER NOT NULL DEFAULT 0,
    XL INTEGER NOT NULL DEFAULT 0,
    LARGE INTEGER NOT NULL DEFAULT 0,
    MEDIUM INTEGER NOT NULL DEFAULT 0,
    SMALL INTEGER NOT NULL DEFAULT 0,
    VOLLEIKG DOUBLE PRECISION NOT NULL DEFAULT 0,
    SCHMUTZ INTEGER NOT NULL DEFAULT 0,
    KNICKEIER INTEGER NOT NULL DEFAULT 0,
    BRUCHEIER INTEGER NOT NULL DEFAULT 0,
    BUCHUNGSTYP TEXT NOT NULL DEFAULT 'E',
    CHARGE VARCHAR(255) NOT NULL DEFAULT '',
    KZ_LAGER VARCHAR(191) NOT NULL DEFAULT 'x',
    ID_FREMDEBUCHUNG INTEGER NOT NULL DEFAULT 0,
    VERKAUF INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE FIRMENPARAMETER (
    ID SERIAL PRIMARY KEY,
    ID_HERDEN INTEGER NOT NULL DEFAULT 0,
    KZ CHAR(1) NOT NULL DEFAULT 'x',
    JUMBOS INTEGER NOT NULL DEFAULT 0,
    KLASSENERFASSEN INTEGER NOT NULL DEFAULT 0,
    KLASSEAERFASSEN INTEGER NOT NULL DEFAULT 0,
    KLASSEAERRECHNEN INTEGER NOT NULL DEFAULT 0,
    KLASSEAVERMITTELN INTEGER NOT NULL DEFAULT 0,
    ERFASSESCHMUTZEI INTEGER NOT NULL DEFAULT 0,
    ERFASSEKNICKEI INTEGER NOT NULL DEFAULT 0,
    ERFASSEBRUCHEI INTEGER NOT NULL DEFAULT 0,
    ERFASSEVOLLEI INTEGER NOT NULL DEFAULT 0,
    MASSVOLLEI INTEGER NOT NULL DEFAULT 0,
    AUFTEILUNGGEWICHT INTEGER NOT NULL DEFAULT 0,
    KONTROLLWIEGUNG INTEGER NOT NULL DEFAULT 0,
    ANZAHLKONTROLLW INTEGER NOT NULL DEFAULT 0,
    VERPACKUNGKG DOUBLE PRECISION NOT NULL DEFAULT 0,
    AUFTEILUNGALTER INTEGER NOT NULL DEFAULT 0,
    ERFASSEVOLLEIKG INTEGER NOT NULL DEFAULT 0,
    LAUFZEITWOCHEN INTEGER NOT NULL DEFAULT 0,
    ZEITSTEMPEL VARCHAR(50) NOT NULL DEFAULT '',
    SCHLACHTERLOESHENNE DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRODUKTIONSDAUER INTEGER NOT NULL DEFAULT 0,
    ID_TABELLEGEWICHT INTEGER NOT NULL DEFAULT 0,
    ID_TABELLEALTER INTEGER NOT NULL DEFAULT 0,
    LEGEBEGINN_LW INTEGER NOT NULL DEFAULT 18,
    VERLUSTEBEIBUCHUNG INTEGER NOT NULL DEFAULT 0,
    LAGERBUCHUNGBEIBUCHUNG INTEGER NOT NULL DEFAULT 0,
    AW INTEGER NOT NULL DEFAULT 0,
    MAXTAGEVERMITTELN INTEGER NOT NULL DEFAULT 0,
    CHARGEJUMBOS INTEGER NOT NULL DEFAULT 0,
    CHARGEXL INTEGER NOT NULL DEFAULT 0,
    CHARGEMEDIUM INTEGER NOT NULL DEFAULT 0,
    CHARGESMALL INTEGER NOT NULL DEFAULT 0,
    CHARGELARGE INTEGER NOT NULL DEFAULT 0,
    CHARGEVOLLEI INTEGER NOT NULL DEFAULT 0,
    CHARGEPREFIXFIRMA VARCHAR(10) NOT NULL DEFAULT '',
    CHARGEPREFIXHERDENNUMMER INTEGER NOT NULL DEFAULT 0,
    CHARGEDATUM INTEGER NOT NULL DEFAULT 0,
    CHARGELAGERNUMMER INTEGER NOT NULL DEFAULT 0,
    CHARGETRENNUNG CHAR(1) NOT NULL DEFAULT '-',
    BEIVERMITTELNDATUMAKTUELL INTEGER NOT NULL DEFAULT 0,
    PSEUDOLAGER INTEGER NOT NULL DEFAULT 0,
    BIO INTEGER NOT NULL DEFAULT 0,
    HALTUNGSTYP CHAR(1) NOT NULL DEFAULT '3',
    BIOAUFSCHLAG DOUBLE PRECISION NOT NULL DEFAULT 0,
    FUTTERINVENTUR INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE FUTTER (
    ID SERIAL PRIMARY KEY,
    ID_SILO INTEGER NOT NULL,
    SILONUMMER INTEGER NOT NULL DEFAULT 0,
    HERDENR INTEGER NOT NULL DEFAULT 0,
    ID_PERSON INTEGER NOT NULL DEFAULT 0,
    LIEFERDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    LIEFERMENGE DOUBLE PRECISION NOT NULL DEFAULT 0,
    PREISDT DOUBLE PRECISION NOT NULL DEFAULT 0,
    RABATTPROZ DOUBLE PRECISION NOT NULL DEFAULT 0,
    NETTO DOUBLE PRECISION NOT NULL DEFAULT 0,
    BRUTTO DOUBLE PRECISION NOT NULL DEFAULT 0,
    MWSTPROZ DOUBLE PRECISION NOT NULL DEFAULT 0,
    MWSTKZ CHAR(1) NOT NULL DEFAULT 'x',
    DATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    ZEITSTEMPEL VARCHAR(50) NOT NULL DEFAULT '',
    ID_FUTTERSORTEN INTEGER NOT NULL DEFAULT 0,
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE HERDEN (
    ID SERIAL PRIMARY KEY,
    ID_SILO INTEGER NOT NULL DEFAULT 0,
    ID_STALL INTEGER NOT NULL DEFAULT 0,
    ID_EILAGER INTEGER NOT NULL DEFAULT 0,
    ID_GEWICHTTAB INTEGER NOT NULL DEFAULT 0,
    ID_ZUECHTER INTEGER NOT NULL DEFAULT 0,
    ID_RASSE INTEGER NOT NULL DEFAULT 0,
    HERDENNUMMER INTEGER UNIQUE NOT NULL DEFAULT 0,
    BEZEICHNUNG VARCHAR(191) NOT NULL DEFAULT '',
    ANFANGSKOSTEN INTEGER NOT NULL DEFAULT 0,
    ANFANGSBESTAND INTEGER NOT NULL DEFAULT 0,
    EINSTALLDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    LEGEDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    EINSTALLKOSTEN DOUBLE PRECISION NOT NULL DEFAULT 0,
    DATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    AKTIV INTEGER NOT NULL DEFAULT 1,
    AW INTEGER NOT NULL DEFAULT 0,
    ALLEBUCHUNGENMITDATUM INTEGER NOT NULL DEFAULT 0,
    ZEITSTEMPEL VARCHAR(50) NOT NULL DEFAULT ''
);

CREATE TABLE KLASSIFIZIERUNG (
    ID SERIAL PRIMARY KEY,
    PREIS DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE VARCHAR(10) NOT NULL DEFAULT '',
    VON INTEGER NOT NULL DEFAULT 0,
    BIS INTEGER NOT NULL DEFAULT 0,
    BEMERKUNG VARCHAR(45) NOT NULL DEFAULT '',
    ZEITSTEMPEL VARCHAR(50) NOT NULL DEFAULT '',
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE KOSTEN (
    ID SERIAL PRIMARY KEY,
    ID_KOSTENTABKOPF INTEGER NOT NULL DEFAULT 1,
    KOSTENTYP CHAR(1) NOT NULL DEFAULT 'x',
    BEZEICHNUNG VARCHAR(25) NOT NULL DEFAULT '',
    KOSTEN DOUBLE PRECISION NOT NULL DEFAULT 0,
    TAGE INTEGER NOT NULL DEFAULT 0,
    BUCHUNGSDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE KOSTENTABKOPF (
    ID SERIAL PRIMARY KEY,
    SCHLACHTERLOES DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRODDAUERGEPLANT INTEGER NOT NULL DEFAULT 0,
    GEBAEUDEWERT DOUBLE PRECISION NOT NULL DEFAULT 0,
    ABSCHREIBUNG_G DOUBLE PRECISION NOT NULL DEFAULT 0,
    GERAETEWERT DOUBLE PRECISION NOT NULL DEFAULT 0,
    ABSCHREIBUNG_R DOUBLE PRECISION NOT NULL DEFAULT 0,
    KOSTENTAG DOUBLE PRECISION NOT NULL DEFAULT 0,
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE LSLKLASSIK (
    ID SERIAL PRIMARY KEY,
    TABELLENNUMMER INTEGER NOT NULL DEFAULT 0,
    ALTERINWOCHEN INTEGER NOT NULL DEFAULT 0,
    EIZAHLKUM DOUBLE PRECISION NOT NULL DEFAULT 0,
    LEGERATEAH DOUBLE PRECISION NOT NULL DEFAULT 0,
    LEGERATEDH DOUBLE PRECISION NOT NULL DEFAULT 0,
    EIGEWICHTWO DOUBLE PRECISION NOT NULL DEFAULT 0,
    EIGEWICHTKUM DOUBLE PRECISION NOT NULL DEFAULT 0,
    EIMASSEWO DOUBLE PRECISION NOT NULL DEFAULT 0,
    EIMASSEKUM DOUBLE PRECISION NOT NULL DEFAULT 0,
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE MWST (
    ID SERIAL PRIMARY KEY,
    MWSTKZ CHAR(1) NOT NULL DEFAULT 'x',
    PROZENT DOUBLE PRECISION NOT NULL DEFAULT 0,
    KONTO VARCHAR(8) NOT NULL DEFAULT '',
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE PERSON (
    ID SERIAL PRIMARY KEY,
    ID_TEXTE INTEGER NOT NULL DEFAULT 0,
    ID_ANREDE INTEGER NOT NULL DEFAULT 0,
    PERSONENNUMMER INTEGER NOT NULL DEFAULT 0,
    POSTFACH VARCHAR(191) NOT NULL DEFAULT '',
    NAME VARCHAR(191) NOT NULL DEFAULT '',
    FIRMA VARCHAR(191) NOT NULL DEFAULT '',
    STRASSE VARCHAR(191) NOT NULL DEFAULT '',
    PLZ VARCHAR(191) NOT NULL DEFAULT '',
    ORT VARCHAR(191) NOT NULL DEFAULT '',
    TELEFON VARCHAR(191) NOT NULL DEFAULT '',
    MOBILTELEPHON VARCHAR(191) NOT NULL DEFAULT '',
    EMAIL VARCHAR(191) NOT NULL DEFAULT '',
    EMAIL2 VARCHAR(191) NOT NULL DEFAULT '',
    FOTO BYTEA,
    KZ VARCHAR(191) NOT NULL DEFAULT 'x',
    HOMEPAGE VARCHAR(191) NOT NULL DEFAULT ''
);

CREATE TABLE RASSE (
    ID SERIAL PRIMARY KEY,
    RASSE VARCHAR(20) NOT NULL DEFAULT '',
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE SILO (
    ID SERIAL PRIMARY KEY,
    SILONUMMER INTEGER NOT NULL DEFAULT 0,
    PERSONENNUMMER INTEGER NOT NULL DEFAULT 0,
    ID_LIEFERANT INTEGER NOT NULL DEFAULT 0,
    BEZEICHNUNG VARCHAR(30) NOT NULL DEFAULT '',
    INVENTURDATUMALT VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    INVENTURDATUMNEU VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    MAXFUELLMENGE INTEGER NOT NULL DEFAULT 0,
    MINFUELLMENGE INTEGER NOT NULL DEFAULT 0,
    INVENTURFUELLMENGE INTEGER NOT NULL DEFAULT 0,
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE STALL (
    ID SERIAL PRIMARY KEY,
    ID_ALT INTEGER NOT NULL DEFAULT 0,
    STALLNUMMER INTEGER NOT NULL DEFAULT 0,
    BEZEICHNUNG VARCHAR(191) NOT NULL DEFAULT ''
);

CREATE TABLE TABELLENKOPF (
    ID SERIAL PRIMARY KEY,
    TABELLENTYP CHAR(1) NOT NULL,
    TABELLENNUMMER INTEGER NOT NULL,
    BEZEICHNUNG VARCHAR(40) NOT NULL DEFAULT '',
    ANLAGEDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    DATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    UNIQUE (TABELLENTYP, TABELLENNUMMER)
);

CREATE TABLE TEXT_TYPEN (
    ID SERIAL PRIMARY KEY,
    KZ VARCHAR(191) UNIQUE NOT NULL DEFAULT 'x',
    BEZEICHNUNG VARCHAR(191) NOT NULL DEFAULT '',
    SYSTEM_KZ INTEGER NOT NULL DEFAULT 0,
    STATUS INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE TEXTE (
    ID SERIAL PRIMARY KEY,
    TEXT_TYP_KZ VARCHAR(191) NOT NULL DEFAULT '',
    KZ CHAR(1) NOT NULL DEFAULT 'x',
    SYSTEM_KZ INTEGER NOT NULL DEFAULT 0,
    STATUS INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (TEXT_TYP_KZ) REFERENCES TEXT_TYPEN (KZ)
);

CREATE TABLE UEBERSETZUNGEN (
    ID_TEXTE INTEGER NOT NULL,
    SPRACHE_KZ VARCHAR(191) NOT NULL,
    BETREFF VARCHAR(191) NOT NULL DEFAULT '',
    INHALT TEXT NOT NULL,
    PRIMARY KEY (ID_TEXTE, SPRACHE_KZ),
    FOREIGN KEY (ID_TEXTE) REFERENCES TEXTE (ID) ON DELETE CASCADE
);

CREATE TABLE TIERBEWEGUNGEN (
    ID SERIAL PRIMARY KEY,
    HERDENNUMMER INTEGER DEFAULT 0,
    ID_BUCHUNG INTEGER DEFAULT 0,
    TYP CHAR(1) DEFAULT 'x',
    ID_TEXTE INTEGER DEFAULT 0,
    BEWEGUNGSDATUM VARCHAR(191) DEFAULT '0001-01-01',
    BEWEGUNGEN INTEGER DEFAULT 0,
    ID_HERDEN_VON INTEGER DEFAULT 0,
    ID_HERDEN_NACH INTEGER DEFAULT 0,
    KOSTEN DOUBLE PRECISION DEFAULT 0
);

CREATE TABLE VERLUSTE (
    ID SERIAL PRIMARY KEY,
    ID_HERDEN INTEGER NOT NULL DEFAULT 0,
    VERLUSTE INTEGER NOT NULL DEFAULT 0,
    HERDENNUMMER INTEGER NOT NULL DEFAULT 0,
    TYP CHAR(1) NOT NULL DEFAULT 'x',
    GRUND INTEGER NOT NULL DEFAULT 0,
    BEWEGUNGSDATUM VARCHAR(25) NOT NULL DEFAULT '0001-01-01',
    AW INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE GEWICHTTABELLE (
    ID SERIAL PRIMARY KEY,
    TABELLENNUMMER INTEGER NOT NULL DEFAULT 0,
    EIGEWICHT DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE1 DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE2 DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE3 DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE4 DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE5 DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE6 DOUBLE PRECISION NOT NULL DEFAULT 0,
    KLASSE7 DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE LAGERPLATZ (
    ID SERIAL PRIMARY KEY,
    ID_EILAGER INTEGER NOT NULL DEFAULT 0,
    BEZEICHNUNG VARCHAR(40) NOT NULL DEFAULT '',
    BEMERKUNG TEXT NOT NULL,
    FOREIGN KEY (ID_EILAGER) REFERENCES EILAGER(ID)
);

CREATE TABLE EIERPREISE (
    ID SERIAL PRIMARY KEY,
    KZ_HALTUNGSTYP CHAR(1) NOT NULL DEFAULT 'x',
    EIERKLASSE VARCHAR(191) NOT NULL DEFAULT '',
    GEWICHT_VON DOUBLE PRECISION NOT NULL DEFAULT 0,
    GEWICHT_BIS DOUBLE PRECISION NOT NULL DEFAULT 0,
    PREIS_VON DOUBLE PRECISION NOT NULL DEFAULT 0,
    PREIS_BIS DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE DYNAMISCHE_SQL (
    ID SERIAL PRIMARY KEY,
    BESCHREIBUNG TEXT NOT NULL,
    SQLSTATEMENT TEXT NOT NULL,
    KATEGORIE_KZ CHAR(1) NOT NULL DEFAULT 'x',
    GRUPPEN_KZ CHAR(1) NOT NULL DEFAULT 'x',
    TYP_KZ CHAR(1) NOT NULL DEFAULT 'x',
    TEMPLATE_NAME VARCHAR(191) NOT NULL DEFAULT '',
    PARAM_DEF VARCHAR(191) NOT NULL DEFAULT '',
    DETAIL_SQL TEXT NOT NULL,
    LINK_LOGIC VARCHAR(191) NOT NULL DEFAULT '',
    GROUP_FIELD VARCHAR(191) NOT NULL DEFAULT '',
    ROWS_PER_PAGE INTEGER NOT NULL DEFAULT 0,
    PAGE_ORIENTATION VARCHAR(191) NOT NULL DEFAULT 'P',
    SHOW_MASTER_GRID INTEGER NOT NULL DEFAULT 0,
    SHOW_DETAIL_GRID INTEGER NOT NULL DEFAULT 0,
    SYSTEM_KZ VARCHAR(191) NOT NULL DEFAULT '0',
    SQLSTATEMENT_NATIVE TEXT NOT NULL,
    DETAIL_SQL_NATIVE TEXT NOT NULL,
    ROOT_KZ CHAR(1) NOT NULL DEFAULT 'x',
    SUMMENZEILE VARCHAR(191) NOT NULL DEFAULT '',
    IST_SUMMENZEILE INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE TRANSLATEFELDNAMEN (
    ID_FELD_KATALOG INTEGER NOT NULL,
    SPRACHE_KZ VARCHAR(191) NOT NULL,
    BETREFF VARCHAR(191) NOT NULL DEFAULT '',
    INHALT TEXT NOT NULL,
    PRIMARY KEY (ID_FELD_KATALOG, SPRACHE_KZ)
);

CREATE TABLE FELD_KATALOG (
    ID SERIAL PRIMARY KEY,
    KZ VARCHAR(191) NOT NULL DEFAULT 'x',
    FELDNAME VARCHAR(191) NOT NULL DEFAULT '',
    NAMEINDB INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE BENUTZERPROFILE (
    ID SERIAL PRIMARY KEY,
    PROFIL_KZ CHAR(1) NOT NULL UNIQUE,
    BESCHREIBUNG TEXT NOT NULL,
    F_DASHBOARD INTEGER NOT NULL DEFAULT 0,
    F_HERDEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_EINRICHTUNGEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_PERSONEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_BUCHUNGEN_ERFASSEN INTEGER NOT NULL DEFAULT 0,
    F_AUSWERTUNGEN_ANZEIGEN INTEGER NOT NULL DEFAULT 0,
    F_SQL_STRUKTUR_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_BENUTZER_PROFILE INTEGER NOT NULL DEFAULT 0,
    F_PARAMETER_EDITIEREN INTEGER NOT NULL DEFAULT 0,
    F_KOSTEN_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_TABELLEN_ANZEIGEN INTEGER NOT NULL DEFAULT 0,
    F_TEXTE_VERWALTEN INTEGER NOT NULL DEFAULT 0,
    F_SYSTEM_VERWALTUNG INTEGER NOT NULL DEFAULT 0,
    F_BACKUP_ERSTELLEN INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE BENUTZER (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(191) NOT NULL UNIQUE,
    PASSWORT VARCHAR(191) NOT NULL,
    KLARNAME VARCHAR(191) NOT NULL DEFAULT '',
    ID_BENUTZER_PROFILE INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_BENUTZER_PROFILE) REFERENCES BENUTZERPROFILE (ID)
);

CREATE TABLE SHOWTV (
    ID SERIAL PRIMARY KEY,
    TVNAME VARCHAR(30) NOT NULL DEFAULT '',
    SHOWIT INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE FUTTERSORTEN (
    ID SERIAL PRIMARY KEY,
    BEZEICHNUNG VARCHAR(191) NOT NULL DEFAULT 'x'
);

CREATE TABLE VERKAUF (
    ID SERIAL PRIMARY KEY,
    ID_EILAGERBUCHUNG INTEGER NOT NULL UNIQUE,
    ID_BUCHUNG INTEGER NOT NULL DEFAULT 0,
    BUCHUNGSDATUM VARCHAR(191) NOT NULL DEFAULT '0001-01-01',
    MENGESMALL INTEGER NOT NULL DEFAULT 0 CHECK (MENGESMALL >= 0),
    MENGEMEDIUM INTEGER NOT NULL DEFAULT 0 CHECK (MENGEMEDIUM >= 0),
    MENGELARGE INTEGER NOT NULL DEFAULT 0 CHECK (MENGELARGE >= 0),
    MENGEXL INTEGER NOT NULL DEFAULT 0 CHECK (MENGEXL >= 0),
    PREISSMALL DOUBLE PRECISION NOT NULL DEFAULT 0.0 CHECK (PREISSMALL >= 0),
    PREISMEDIUM DOUBLE PRECISION NOT NULL DEFAULT 0.0 CHECK (PREISMEDIUM >= 0),
    PREISLARGE DOUBLE PRECISION NOT NULL DEFAULT 0.0 CHECK (PREISLARGE >= 0),
    PREISXL DOUBLE PRECISION NOT NULL DEFAULT 0.0 CHECK (PREISXL >= 0),
    GESAMTPREIS DOUBLE PRECISION NOT NULL DEFAULT 0.0 CHECK (GESAMTPREIS >= 0),
    BIO SMALLINT NOT NULL DEFAULT 0,
    VERBUCHT SMALLINT NOT NULL DEFAULT 0,
    CHARGE VARCHAR(25) NOT NULL DEFAULT '',
    RABATTPROZENT DOUBLE PRECISION NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_EILAGERBUCHUNG) REFERENCES EILAGERBUCHUNG (ID) ON DELETE CASCADE
);

CREATE TABLE SYSTEMSETTINGS (
    NAME VARCHAR(191) PRIMARY KEY,
    VALUE TEXT NOT NULL
);

CREATE TABLE USER_STATE (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(191) NOT NULL,
    KEY VARCHAR(191) NOT NULL,
    VALUE TEXT NOT NULL,
    UNIQUE(USERNAME, KEY)
);

CREATE TABLE AKTIONEN (
    ID SERIAL PRIMARY KEY,
    AKTIONEN_KZ CHAR(1),
    ID_USER INTEGER DEFAULT 0,
    AKTIONSDATUM VARCHAR(25) DEFAULT '0001-01-01',
    BEZEICHNUNG TEXT,
    INTERVALL_TAGE INTEGER DEFAULT 0,
    ANZAHL_INTERVALLE INTEGER DEFAULT 0,
    ERLEDIGT INTEGER DEFAULT 0,
    ID_USER_ERLEDIGT INTEGER DEFAULT 0,
    ERLEDIGT_AM VARCHAR(25),
    BEMERKUNG TEXT
);
