// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repo

import (
	"database/sql"
)

type Aktionen struct {
	ID               int64          `json:"id"`
	AktionenKz       interface{}    `json:"aktionen_kz"`
	IDUser           sql.NullInt64  `json:"id_user"`
	Aktionsdatum     sql.NullString `json:"aktionsdatum"`
	Bezeichnung      sql.NullString `json:"bezeichnung"`
	IntervallTage    sql.NullInt64  `json:"intervall_tage"`
	AnzahlIntervalle sql.NullInt64  `json:"anzahl_intervalle"`
	Erledigt         sql.NullInt64  `json:"erledigt"`
	IDUserErledigt   sql.NullInt64  `json:"id_user_erledigt"`
	ErledigtAm       sql.NullString `json:"erledigt_am"`
	Bemerkung        sql.NullString `json:"bemerkung"`
}

type Benutzer struct {
	ID                int64  `json:"id"`
	Username          string `json:"username"`
	Passwort          string `json:"passwort"`
	Klarname          string `json:"klarname"`
	IDBenutzerProfile int64  `json:"id_benutzer_profile"`
}

type Benutzerprofile struct {
	ID                      int64       `json:"id"`
	ProfilKz                interface{} `json:"profil_kz"`
	Beschreibung            string      `json:"beschreibung"`
	FDashboard              int64       `json:"f_dashboard"`
	FHerdenVerwalten        int64       `json:"f_herden_verwalten"`
	FEinrichtungenVerwalten int64       `json:"f_einrichtungen_verwalten"`
	FPersonenVerwalten      int64       `json:"f_personen_verwalten"`
	FBuchungenErfassen      int64       `json:"f_buchungen_erfassen"`
	FAuswertungenAnzeigen   int64       `json:"f_auswertungen_anzeigen"`
	FSqlStrukturVerwalten   int64       `json:"f_sql_struktur_verwalten"`
	FBenutzerProfile        int64       `json:"f_benutzer_profile"`
	FParameterEditieren     int64       `json:"f_parameter_editieren"`
	FKostenVerwalten        int64       `json:"f_kosten_verwalten"`
	FTabellenAnzeigen       int64       `json:"f_tabellen_anzeigen"`
	FTexteVerwalten         int64       `json:"f_texte_verwalten"`
	FSystemVerwaltung       int64       `json:"f_system_verwaltung"`
	FBackupErstellen        int64       `json:"f_backup_erstellen"`
}

type Buchung struct {
	ID                  int64       `json:"id"`
	IDHerden            int64       `json:"id_herden"`
	Lw                  int64       `json:"lw"`
	Herdennummer        int64       `json:"herdennummer"`
	Buchungsdatum       string      `json:"buchungsdatum"`
	Gewichtprobe        int64       `json:"gewichtprobe"`
	Kontrollgewicht     float64     `json:"kontrollgewicht"`
	Klassea             int64       `json:"klassea"`
	Verluste            int64       `json:"verluste"`
	Eimasse             float64     `json:"eimasse"`
	Schmutz             int64       `json:"schmutz"`
	Knickeier           int64       `json:"knickeier"`
	Vollei              float64     `json:"vollei"`
	Brucheier           int64       `json:"brucheier"`
	Tierbestand         int64       `json:"tierbestand"`
	IDEitabelle         int64       `json:"id_eitabelle"`
	IDDgewichttab       int64       `json:"id_dgewichttab"`
	Futterktag          int64       `json:"futterktag"`
	Silonr              int64       `json:"silonr"`
	Kl6                 int64       `json:"kl6"`
	Vermitteltam        string      `json:"vermitteltam"`
	Small               int64       `json:"small"`
	Large               int64       `json:"large"`
	Medium              int64       `json:"medium"`
	Xl                  int64       `json:"xl"`
	Zeitstempel         string      `json:"zeitstempel"`
	Dgewichtei          float64     `json:"dgewichtei"`
	Aw                  int64       `json:"aw"`
	Vermittelt          interface{} `json:"vermittelt"`
	Futterverbrauchtier int64       `json:"futterverbrauchtier"`
}

type DynamischeSql struct {
	ID                 int64       `json:"id"`
	Beschreibung       string      `json:"beschreibung"`
	Sqlstatement       string      `json:"sqlstatement"`
	KategorieKz        interface{} `json:"kategorie_kz"`
	GruppenKz          interface{} `json:"gruppen_kz"`
	TypKz              interface{} `json:"typ_kz"`
	TemplateName       string      `json:"template_name"`
	ParamDef           string      `json:"param_def"`
	DetailSql          string      `json:"detail_sql"`
	LinkLogic          string      `json:"link_logic"`
	GroupField         string      `json:"group_field"`
	RowsPerPage        int64       `json:"rows_per_page"`
	PageOrientation    string      `json:"page_orientation"`
	ShowMasterGrid     int64       `json:"show_master_grid"`
	ShowDetailGrid     int64       `json:"show_detail_grid"`
	SystemKz           string      `json:"system"`
	SqlstatementNative string      `json:"sqlstatement_native"`
	DetailSqlNative    string      `json:"detail_sql_native"`
	RootKz             interface{} `json:"root_kz"`
	Summenzeile        string      `json:"summenzeile"`
	IstSummenzeile     int64       `json:"ist_summenzeile"`
}

type Eierpreise struct {
	ID            int64       `json:"id"`
	KzHaltungstyp interface{} `json:"kz_haltungstyp"`
	Eierklasse    string      `json:"eierklasse"`
	GewichtVon    interface{} `json:"gewicht_von"`
	GewichtBis    interface{} `json:"gewicht_bis"`
	PreisVon      interface{} `json:"preis_von"`
	PreisBis      interface{} `json:"preis_bis"`
}

type Eilager struct {
	ID            int64       `json:"id"`
	Lagernummer   int64       `json:"lagernummer"`
	Kz            interface{} `json:"kz"`
	Bezeichnung   string      `json:"bezeichnung"`
	LetzteBuchung string      `json:"letzte_buchung"`
	Jumbos        interface{} `json:"jumbos"`
	Xl            interface{} `json:"xl"`
	Large         interface{} `json:"large"`
	Medium        interface{} `json:"medium"`
	Small         interface{} `json:"small"`
	Volleikg      float64     `json:"volleikg"`
	Klasse6       string      `json:"klasse6"`
	Klasse7       string      `json:"klasse7"`
	Aw            int64       `json:"aw"`
}

type Eilagerbuchung struct {
	ID              int64   `json:"id"`
	IDFremdeslager  int64   `json:"id_fremdeslager"`
	IDBuchung       int64   `json:"id_buchung"`
	IDEilager       int64   `json:"id_eilager"`
	Buchungsdatum   string  `json:"buchungsdatum"`
	Jumbos          int64   `json:"jumbos"`
	Xl              int64   `json:"xl"`
	Large           int64   `json:"large"`
	Medium          int64   `json:"medium"`
	Small           int64   `json:"small"`
	Volleikg        float64 `json:"volleikg"`
	Schmutz         int64   `json:"schmutz"`
	Knickeier       int64   `json:"knickeier"`
	Brucheier       int64   `json:"brucheier"`
	Buchungstyp     string  `json:"buchungstyp"`
	Charge          string  `json:"charge"`
	KzLager         string  `json:"kz_lager"`
	IDFremdebuchung int64   `json:"id_fremdebuchung"`
	Verkauf         int64   `json:"verkauf"`
}

type FeldKatalog struct {
	ID       int64  `json:"id"`
	Kz       string `json:"kz"`
	Feldname string `json:"feldname"`
	Nameindb int64  `json:"nameindb"`
}

type Firmenparameter struct {
	ID                        int64       `json:"id"`
	IDHerden                  int64       `json:"id_herden"`
	Kz                        interface{} `json:"kz"`
	Jumbos                    int64       `json:"jumbos"`
	Klassenerfassen           int64       `json:"klassenerfassen"`
	Klasseaerfassen           int64       `json:"klasseaerfassen"`
	Klasseaerrechnen          int64       `json:"klasseaerrechnen"`
	Klasseavermitteln         int64       `json:"klasseavermitteln"`
	Erfasseschmutzei          int64       `json:"erfasseschmutzei"`
	Erfasseknickei            int64       `json:"erfasseknickei"`
	Erfassebruchei            int64       `json:"erfassebruchei"`
	Erfassevollei             int64       `json:"erfassevollei"`
	Massvollei                int64       `json:"massvollei"`
	Aufteilunggewicht         int64       `json:"aufteilunggewicht"`
	Kontrollwiegung           int64       `json:"kontrollwiegung"`
	Anzahlkontrollw           int64       `json:"anzahlkontrollw"`
	Verpackungkg              float64     `json:"verpackungkg"`
	Aufteilungalter           int64       `json:"aufteilungalter"`
	Erfassevolleikg           int64       `json:"erfassevolleikg"`
	Laufzeitwochen            int64       `json:"laufzeitwochen"`
	Zeitstempel               string      `json:"zeitstempel"`
	Schlachterloeshenne       float64     `json:"schlachterloeshenne"`
	Produktionsdauer          int64       `json:"produktionsdauer"`
	IDTabellegewicht          int64       `json:"id_tabellegewicht"`
	IDTabellealter            int64       `json:"id_tabellealter"`
	LegebeginnLw              int64       `json:"legebeginn_lw"`
	Verlustebeibuchung        int64       `json:"verlustebeibuchung"`
	Lagerbuchungbeibuchung    int64       `json:"lagerbuchungbeibuchung"`
	Aw                        int64       `json:"aw"`
	Maxtagevermitteln         int64       `json:"maxtagevermitteln"`
	Chargejumbos              int64       `json:"chargejumbos"`
	Chargexl                  int64       `json:"chargexl"`
	Chargemedium              int64       `json:"chargemedium"`
	Chargesmall               int64       `json:"chargesmall"`
	Chargelarge               int64       `json:"chargelarge"`
	Chargevollei              int64       `json:"chargevollei"`
	Chargeprefixfirma         interface{} `json:"chargeprefixfirma"`
	Chargeprefixherdennummer  int64       `json:"chargeprefixherdennummer"`
	Chargedatum               int64       `json:"chargedatum"`
	Chargelagernummer         int64       `json:"chargelagernummer"`
	Chargetrennung            interface{} `json:"chargetrennung"`
	Beivermittelndatumaktuell int64       `json:"beivermittelndatumaktuell"`
	Pseudolager               int64       `json:"pseudolager"`
	Bio                       int64       `json:"bio"`
	Haltungstyp               interface{} `json:"haltungstyp"`
	Bioaufschlag              interface{} `json:"bioaufschlag"`
	Futterinventur            int64       `json:"futterinventur"`
}

type Futter struct {
	ID             int64       `json:"id"`
	IDSilo         int64       `json:"id_silo"`
	Silonummer     int64       `json:"silonummer"`
	Herdenr        int64       `json:"herdenr"`
	IDPerson       int64       `json:"id_person"`
	Lieferdatum    string      `json:"lieferdatum"`
	Liefermenge    float64     `json:"liefermenge"`
	Preisdt        float64     `json:"preisdt"`
	Rabattproz     float64     `json:"rabattproz"`
	Netto          float64     `json:"netto"`
	Brutto         float64     `json:"brutto"`
	Mwstproz       float64     `json:"mwstproz"`
	Mwstkz         interface{} `json:"mwstkz"`
	Datum          string      `json:"datum"`
	Zeitstempel    string      `json:"zeitstempel"`
	IDFuttersorten int64       `json:"id_futtersorten"`
	Aw             int64       `json:"aw"`
}

type Futtersorten struct {
	ID          int64  `json:"id"`
	Bezeichnung string `json:"bezeichnung"`
}

type Gewichttabelle struct {
	ID             int64   `json:"id"`
	Tabellennummer int64   `json:"tabellennummer"`
	Eigewicht      float64 `json:"eigewicht"`
	Klasse1        float64 `json:"klasse1"`
	Klasse2        float64 `json:"klasse2"`
	Klasse3        float64 `json:"klasse3"`
	Klasse4        float64 `json:"klasse4"`
	Klasse5        float64 `json:"klasse5"`
	Klasse6        float64 `json:"klasse6"`
	Klasse7        float64 `json:"klasse7"`
}

type Herden struct {
	ID                    int64   `json:"id"`
	IDSilo                int64   `json:"id_silo"`
	IDStall               int64   `json:"id_stall"`
	IDEilager             int64   `json:"id_eilager"`
	IDGewichttab          int64   `json:"id_gewichttab"`
	IDZuechter            int64   `json:"id_zuechter"`
	IDRasse               int64   `json:"id_rasse"`
	Herdennummer          int64   `json:"herdennummer"`
	Bezeichnung           string  `json:"bezeichnung"`
	Anfangskosten         int64   `json:"anfangskosten"`
	Anfangsbestand        int64   `json:"anfangsbestand"`
	Einstalldatum         string  `json:"einstalldatum"`
	Legedatum             string  `json:"legedatum"`
	Einstallkosten        float64 `json:"einstallkosten"`
	Datum                 string  `json:"datum"`
	Aktiv                 int64   `json:"aktiv"`
	Aw                    int64   `json:"aw"`
	Allebuchungenmitdatum int64   `json:"allebuchungenmitdatum"`
}

type Klassifizierung struct {
	ID          int64   `json:"id"`
	Preis       float64 `json:"preis"`
	Klasse      string  `json:"klasse"`
	Von         int64   `json:"von"`
	Bis         int64   `json:"bis"`
	Bemerkung   string  `json:"bemerkung"`
	Zeitstempel string  `json:"zeitstempel"`
	Aw          int64   `json:"aw"`
}

type Kosten struct {
	ID              int64       `json:"id"`
	IDKostentabkopf int64       `json:"id_kostentabkopf"`
	Kostentyp       interface{} `json:"kostentyp"`
	Bezeichnung     string      `json:"bezeichnung"`
	Kosten          float64     `json:"kosten"`
	Tage            int64       `json:"tage"`
	Buchungsdatum   string      `json:"buchungsdatum"`
	Aw              int64       `json:"aw"`
}

type Kostentabkopf struct {
	ID               int64   `json:"id"`
	Schlachterloes   float64 `json:"schlachterloes"`
	Proddauergeplant int64   `json:"proddauergeplant"`
	Gebaeudewert     float64 `json:"gebaeudewert"`
	AbschreibungG    float64 `json:"abschreibung_g"`
	Geraetewert      float64 `json:"geraetewert"`
	AbschreibungR    float64 `json:"abschreibung_r"`
	Kostentag        float64 `json:"kostentag"`
	Aw               int64   `json:"aw"`
}

type Lagerplatz struct {
	ID          int64       `json:"id"`
	IDEilager   int64       `json:"id_eilager"`
	Bezeichnung interface{} `json:"bezeichnung"`
	Bemerkung   string      `json:"bemerkung"`
}

type Lslklassik struct {
	ID             int64   `json:"id"`
	Tabellennummer int64   `json:"tabellennummer"`
	Alterinwochen  int64   `json:"alterinwochen"`
	Eizahlkum      float64 `json:"eizahlkum"`
	Legerateah     float64 `json:"legerateah"`
	Legeratedh     float64 `json:"legeratedh"`
	Eigewichtwo    float64 `json:"eigewichtwo"`
	Eigewichtkum   float64 `json:"eigewichtkum"`
	Eimassewo      float64 `json:"eimassewo"`
	Eimassekum     float64 `json:"eimassekum"`
	Aw             int64   `json:"aw"`
}

type Mwst struct {
	ID      int64       `json:"id"`
	Mwstkz  interface{} `json:"mwstkz"`
	Prozent float64     `json:"prozent"`
	Konto   string      `json:"konto"`
	Aw      int64       `json:"aw"`
}

type Person struct {
	ID             int64  `json:"id"`
	IDTexte        int64  `json:"id_texte"`
	IDAnrede       int64  `json:"id_anrede"`
	Personennummer int64  `json:"personennummer"`
	Postfach       string `json:"postfach"`
	Name           string `json:"name"`
	Firma          string `json:"firma"`
	Strasse        string `json:"strasse"`
	Plz            string `json:"plz"`
	Ort            string `json:"ort"`
	Telefon        string `json:"telefon"`
	Mobiltelephon  string `json:"mobiltelephon"`
	Email          string `json:"email"`
	Email2         string `json:"email2"`
	Foto           []byte `json:"foto"`
	Kz             string `json:"kz"`
	Homepage       string `json:"homepage"`
}

type Rasse struct {
	ID    int64  `json:"id"`
	Rasse string `json:"rasse"`
	Aw    int64  `json:"aw"`
}

type Showtv struct {
	ID     int64       `json:"id"`
	Tvname interface{} `json:"tvname"`
	Showit int64       `json:"showit"`
}

type Silo struct {
	ID                 int64  `json:"id"`
	Silonummer         int64  `json:"silonummer"`
	Personennummer     int64  `json:"personennummer"`
	IDLieferant        int64  `json:"id_lieferant"`
	Bezeichnung        string `json:"bezeichnung"`
	Inventurdatumalt   string `json:"inventurdatumalt"`
	Inventurdatumneu   string `json:"inventurdatumneu"`
	Maxfuellmenge      int64  `json:"maxfuellmenge"`
	Minfuellmenge      int64  `json:"minfuellmenge"`
	Inventurfuellmenge int64  `json:"inventurfuellmenge"`
	Aw                 int64  `json:"aw"`
}

type Stall struct {
	ID          int64  `json:"id"`
	IDAlt       int64  `json:"id_alt"`
	Stallnummer int64  `json:"stallnummer"`
	Bezeichnung string `json:"bezeichnung"`
}

type Tabellenkopf struct {
	ID             int64       `json:"id"`
	Tabellentyp    interface{} `json:"tabellentyp"`
	Tabellennummer int64       `json:"tabellennummer"`
	Bezeichnung    string      `json:"bezeichnung"`
	Anlagedatum    string      `json:"anlagedatum"`
	Datum          string      `json:"datum"`
}

type TextTypen struct {
	ID          int64  `json:"id"`
	Kz          string `json:"kz"`
	Bezeichnung string `json:"bezeichnung"`
	SystemKz    int64  `json:"system"`
	Status      int64  `json:"status"`
}

type Texte struct {
	ID        int64       `json:"id"`
	TextTypKz string      `json:"text_typ_kz"`
	Kz        interface{} `json:"kz"`
	SystemKz  int64       `json:"system"`
	Status    int64       `json:"status"`
}

type Tierbewegungen struct {
	ID             int64           `json:"id"`
	Herdennummer   sql.NullInt64   `json:"herdennummer"`
	IDBuchung      sql.NullInt64   `json:"id_buchung"`
	Typ            interface{}     `json:"typ"`
	IDTexte        sql.NullInt64   `json:"id_texte"`
	Bewegungsdatum sql.NullString  `json:"bewegungsdatum"`
	Bewegungen     sql.NullInt64   `json:"bewegungen"`
	IDHerdenVon    sql.NullInt64   `json:"id_herden_von"`
	IDHerdenNach   sql.NullInt64   `json:"id_herden_nach"`
	Kosten         sql.NullFloat64 `json:"kosten"`
}

type Translatefeldnamen struct {
	IDFeldKatalog int64  `json:"id_feld_katalog"`
	SpracheKz     string `json:"sprache_kz"`
	Betreff       string `json:"betreff"`
	Inhalt        string `json:"inhalt"`
}

type Uebersetzungen struct {
	IDTexte   int64  `json:"id_texte"`
	SpracheKz string `json:"sprache_kz"`
	Betreff   string `json:"betreff"`
	Inhalt    string `json:"inhalt"`
}

type Verkauf struct {
	ID               int64       `json:"id"`
	IDEilagerbuchung int64       `json:"id_eilagerbuchung"`
	IDBuchung        int64       `json:"id_buchung"`
	Buchungsdatum    string      `json:"buchungsdatum"`
	Mengesmall       int64       `json:"mengesmall"`
	Mengemedium      int64       `json:"mengemedium"`
	Mengelarge       int64       `json:"mengelarge"`
	Mengexl          int64       `json:"mengexl"`
	Preissmall       float64     `json:"preissmall"`
	Preismedium      float64     `json:"preismedium"`
	Preislarge       float64     `json:"preislarge"`
	Preisxl          float64     `json:"preisxl"`
	Gesamtpreis      float64     `json:"gesamtpreis"`
	Bio              bool        `json:"bio"`
	Verbucht         bool        `json:"verbucht"`
	Charge           interface{} `json:"charge"`
	Rabattprozent    interface{} `json:"rabattprozent"`
}

type Verluste struct {
	ID             int64       `json:"id"`
	IDHerden       int64       `json:"id_herden"`
	Verluste       int64       `json:"verluste"`
	Herdennummer   int64       `json:"herdennummer"`
	Typ            interface{} `json:"typ"`
	Grund          int64       `json:"grund"`
	Bewegungsdatum string      `json:"bewegungsdatum"`
	Aw             int64       `json:"aw"`
}
