// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repo

import (
	"context"
)

type Querier interface {
	AddEilagerBuchung(ctx context.Context, arg AddEilagerBuchungParams) (Eilagerbuchung, error)
	AdjustHerdeStock(ctx context.Context, arg AdjustHerdeStockParams) error
	CreateAktion(ctx context.Context, arg CreateAktionParams) (Aktionen, error)
	CreateBenutzer(ctx context.Context, arg CreateBenutzerParams) (Benutzer, error)
	CreateBenutzerProfil(ctx context.Context, arg CreateBenutzerProfilParams) (Benutzerprofile, error)
	CreateBuchung(ctx context.Context, arg CreateBuchungParams) (Buchung, error)
	CreateDynamischeSQL(ctx context.Context, arg CreateDynamischeSQLParams) (DynamischeSql, error)
	CreateEierpreis(ctx context.Context, arg CreateEierpreisParams) (Eierpreise, error)
	CreateEilager(ctx context.Context, arg CreateEilagerParams) (Eilager, error)
	CreateFieldKatalog(ctx context.Context, arg CreateFieldKatalogParams) (FeldKatalog, error)
	CreateFirmenparameter(ctx context.Context, arg CreateFirmenparameterParams) (Firmenparameter, error)
	CreateFutterBuchung(ctx context.Context, arg CreateFutterBuchungParams) (Futter, error)
	CreateFuttersorte(ctx context.Context, bezeichnung string) (Futtersorten, error)
	CreateGewichtTabelle(ctx context.Context, arg CreateGewichtTabelleParams) (Gewichttabelle, error)
	CreateHerde(ctx context.Context, arg CreateHerdeParams) (Herden, error)
	CreateHerdeChecked(ctx context.Context) (Herden, error)
	CreateKosten(ctx context.Context, arg CreateKostenParams) (Kosten, error)
	CreateLSLKlassik(ctx context.Context, arg CreateLSLKlassikParams) (Lslklassik, error)
	CreateLagerplatz(ctx context.Context, arg CreateLagerplatzParams) (Lagerplatz, error)
	CreateMwst(ctx context.Context, arg CreateMwstParams) (Mwst, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreateRasse(ctx context.Context, rasse string) (Rasse, error)
	CreateShowTV(ctx context.Context, arg CreateShowTVParams) (Showtv, error)
	CreateSilo(ctx context.Context, arg CreateSiloParams) (Silo, error)
	CreateStall(ctx context.Context, arg CreateStallParams) (Stall, error)
	CreateTabellenkopf(ctx context.Context, arg CreateTabellenkopfParams) (Tabellenkopf, error)
	CreateText(ctx context.Context, arg CreateTextParams) (Texte, error)
	CreateTextTyp(ctx context.Context, arg CreateTextTypParams) (TextTypen, error)
	CreateTierbewegung(ctx context.Context, arg CreateTierbewegungParams) (Tierbewegungen, error)
	CreateUebersetzung(ctx context.Context, arg CreateUebersetzungParams) (Uebersetzungen, error)
	CreateVerkauf(ctx context.Context, arg CreateVerkaufParams) (Verkauf, error)
	DeleteAktion(ctx context.Context, id int64) error
	DeleteBenutzer(ctx context.Context, id int64) error
	DeleteBenutzerProfil(ctx context.Context, profilKz interface{}) error
	DeleteBuchung(ctx context.Context, id int64) error
	DeleteDynamischeSQL(ctx context.Context, id int64) error
	DeleteEierpreis(ctx context.Context, id int64) error
	DeleteEilager(ctx context.Context, id int64) error
	DeleteEilagerBuchung(ctx context.Context, id int64) error
	DeleteFieldKatalog(ctx context.Context, id int64) error
	DeleteFirmenparameter(ctx context.Context, idHerden int64) error
	DeleteFutterBuchung(ctx context.Context, id int64) error
	DeleteFuttersorte(ctx context.Context, id int64) error
	DeleteGewichtTabelle(ctx context.Context, id int64) error
	DeleteHerde(ctx context.Context, id int64) error
	DeleteKosten(ctx context.Context, id int64) error
	DeleteLSLKlassik(ctx context.Context, id int64) error
	DeleteLagerplatz(ctx context.Context, id int64) error
	DeleteMwst(ctx context.Context, id int64) error
	DeletePerson(ctx context.Context, id int64) error
	DeleteRasse(ctx context.Context, id int64) error
	DeleteShowTV(ctx context.Context, id int64) error
	DeleteSilo(ctx context.Context, id int64) error
	DeleteStall(ctx context.Context, id int64) error
	DeleteText(ctx context.Context, id int64) error
	DeleteTextTyp(ctx context.Context, id int64) error
	DeleteTierbewegung(ctx context.Context, id int64) error
	DeleteVerkauf(ctx context.Context, id int64) error
	DeleteVerkaufByEilagerbuchung(ctx context.Context, idEilagerbuchung int64) error
	GetAktion(ctx context.Context, id int64) (Aktionen, error)
	GetBenutzerByUsername(ctx context.Context, username string) (Benutzer, error)
	GetBenutzerProfilByID(ctx context.Context, id int64) (Benutzerprofile, error)
	GetBenutzerProfilByKZ(ctx context.Context, profilKz interface{}) (Benutzerprofile, error)
	GetBestandsuebersicht(ctx context.Context, arg GetBestandsuebersichtParams) ([]GetBestandsuebersichtRow, error)
	GetBuchung(ctx context.Context, id int64) (Buchung, error)
	GetBuchungGroupTotals(ctx context.Context, arg GetBuchungGroupTotalsParams) (GetBuchungGroupTotalsRow, error)
	GetCompanyPerson(ctx context.Context) (Person, error)
	GetDynamischeSQL(ctx context.Context, id int64) (DynamischeSql, error)
	GetEggBookingYears(ctx context.Context, arg GetEggBookingYearsParams) ([]interface{}, error)
	GetEggStatsByHerde(ctx context.Context, arg GetEggStatsByHerdeParams) (GetEggStatsByHerdeRow, error)
	GetEggStatsByHerdeFiltered(ctx context.Context, arg GetEggStatsByHerdeFilteredParams) (GetEggStatsByHerdeFilteredRow, error)
	GetEggStatsWeeklyByHerde(ctx context.Context, idHerden int64) ([]GetEggStatsWeeklyByHerdeRow, error)
	GetEierpreis(ctx context.Context, id int64) (Eierpreise, error)
	GetEilager(ctx context.Context, id int64) (Eilager, error)
	GetEilagerBuchung(ctx context.Context, id int64) (Eilagerbuchung, error)
	GetEilagerGroupTotals(ctx context.Context, arg GetEilagerGroupTotalsParams) (GetEilagerGroupTotalsRow, error)
	GetEilagerSumByBuchungID(ctx context.Context, idBuchung int64) (GetEilagerSumByBuchungIDRow, error)
	GetEilagerSumBySource(ctx context.Context, arg GetEilagerSumBySourceParams) (GetEilagerSumBySourceRow, error)
	GetFirmenparameterByHerde(ctx context.Context, idHerden int64) (Firmenparameter, error)
	GetGewichtByTabNumAndWeight(ctx context.Context, arg GetGewichtByTabNumAndWeightParams) (Gewichttabelle, error)
	GetGlobalFirmenparameter(ctx context.Context) (Firmenparameter, error)
	GetHerde(ctx context.Context, id int64) (Herden, error)
	GetKostentabkopf(ctx context.Context) (Kostentabkopf, error)
	GetLSLByTabNumAndAge(ctx context.Context, arg GetLSLByTabNumAndAgeParams) (Lslklassik, error)
	GetLagerplatz(ctx context.Context, id int64) (Lagerplatz, error)
	GetLatestBookingByHerde(ctx context.Context, idHerden int64) (GetLatestBookingByHerdeRow, error)
	GetMwst(ctx context.Context, id int64) (Mwst, error)
	GetPerson(ctx context.Context, id int64) (Person, error)
	GetRasse(ctx context.Context, id int64) (Rasse, error)
	GetShowTV(ctx context.Context, id int64) (Showtv, error)
	GetSilo(ctx context.Context, id int64) (Silo, error)
	GetStall(ctx context.Context, id int64) (Stall, error)
	GetTabellenkopf(ctx context.Context, id int64) (Tabellenkopf, error)
	GetTranslatedText(ctx context.Context, arg GetTranslatedTextParams) (GetTranslatedTextRow, error)
	GetVerkauf(ctx context.Context, id int64) (Verkauf, error)
	GetVerkaufByEilagerbuchung(ctx context.Context, idEilagerbuchung int64) (Verkauf, error)
	IncreaseHerdeStockAndCosts(ctx context.Context, arg IncreaseHerdeStockAndCostsParams) error
	IncreaseHerdeStockById(ctx context.Context, arg IncreaseHerdeStockByIdParams) error
	ListAktionen(ctx context.Context, arg ListAktionenParams) ([]ListAktionenRow, error)
	ListBenutzer(ctx context.Context) ([]ListBenutzerRow, error)
	ListBenutzerProfile(ctx context.Context) ([]Benutzerprofile, error)
	ListBuchungen(ctx context.Context) ([]ListBuchungenRow, error)
	ListBuchungenWithHerde(ctx context.Context) ([]ListBuchungenWithHerdeRow, error)
	ListDynamischeSQL(ctx context.Context) ([]ListDynamischeSQLRow, error)
	ListEierpreise(ctx context.Context) ([]Eierpreise, error)
	ListEilager(ctx context.Context) ([]ListEilagerRow, error)
	ListEilagerBuchungenByKZ(ctx context.Context, kz interface{}) ([]Eilagerbuchung, error)
	ListEilagerBuchungenByLager(ctx context.Context, lagerID int64) ([]Eilagerbuchung, error)
	ListFieldTranslations(ctx context.Context, spracheKz string) ([]ListFieldTranslationsRow, error)
	ListFutterBuchungen(ctx context.Context) ([]ListFutterBuchungenRow, error)
	ListFuttersorten(ctx context.Context) ([]Futtersorten, error)
	ListGewichtByTabNum(ctx context.Context, tabellennummer int64) ([]Gewichttabelle, error)
	ListHerden(ctx context.Context) ([]ListHerdenRow, error)
	ListHerdenDetailed(ctx context.Context) ([]ListHerdenDetailedRow, error)
	ListHerdenLookup(ctx context.Context) ([]ListHerdenLookupRow, error)
	ListKosten(ctx context.Context) ([]Kosten, error)
	ListLSLKlassikByTabNum(ctx context.Context, tabellennummer int64) ([]Lslklassik, error)
	ListLagerplaetze(ctx context.Context) ([]ListLagerplaetzeRow, error)
	ListLagerplaetzeByEilager(ctx context.Context, idEilager int64) ([]ListLagerplaetzeByEilagerRow, error)
	ListLieferanten(ctx context.Context) ([]Person, error)
	ListMwst(ctx context.Context) ([]Mwst, error)
	ListPersonen(ctx context.Context) ([]Person, error)
	ListRassen(ctx context.Context) ([]Rasse, error)
	ListShowTV(ctx context.Context) ([]Showtv, error)
	ListSilos(ctx context.Context) ([]Silo, error)
	ListSolltabellen(ctx context.Context) ([]ListSolltabellenRow, error)
	ListStaelle(ctx context.Context) ([]Stall, error)
	ListTabellenkopfByType(ctx context.Context, tabellentyp interface{}) ([]Tabellenkopf, error)
	ListTextTypen(ctx context.Context) ([]TextTypen, error)
	ListTexte(ctx context.Context, spracheKz string) ([]ListTexteRow, error)
	ListTexteByKZ(ctx context.Context, arg ListTexteByKZParams) ([]ListTexteByKZRow, error)
	ListTexteByType(ctx context.Context, arg ListTexteByTypeParams) ([]ListTexteByTypeRow, error)
	ListTierbewegungen(ctx context.Context, spracheKz string) ([]ListTierbewegungenRow, error)
	ListTranslateFeldnamen(ctx context.Context, spracheKz string) ([]ListTranslateFeldnamenRow, error)
	ListVerkauf(ctx context.Context) ([]Verkauf, error)
	ListVerwendungsTexte(ctx context.Context, spracheKz string) ([]ListVerwendungsTexteRow, error)
	ListZuechter(ctx context.Context) ([]Person, error)
	UpdateAktion(ctx context.Context, arg UpdateAktionParams) (Aktionen, error)
	UpdateBenutzer(ctx context.Context, arg UpdateBenutzerParams) error
	UpdateBenutzerProfil(ctx context.Context, arg UpdateBenutzerProfilParams) (Benutzerprofile, error)
	UpdateBuchung(ctx context.Context, arg UpdateBuchungParams) (Buchung, error)
	UpdateBuchungStock(ctx context.Context, arg UpdateBuchungStockParams) error
	UpdateBuchungStockById(ctx context.Context, arg UpdateBuchungStockByIdParams) error
	UpdateDynamischeSQL(ctx context.Context, arg UpdateDynamischeSQLParams) (DynamischeSql, error)
	UpdateEierpreis(ctx context.Context, arg UpdateEierpreisParams) (Eierpreise, error)
	UpdateEilager(ctx context.Context, arg UpdateEilagerParams) (Eilager, error)
	UpdateEilagerBuchung(ctx context.Context, arg UpdateEilagerBuchungParams) (Eilagerbuchung, error)
	UpdateFirmenparameter(ctx context.Context, arg UpdateFirmenparameterParams) (Firmenparameter, error)
	UpdateFutterBuchung(ctx context.Context, arg UpdateFutterBuchungParams) (Futter, error)
	UpdateFuttersorte(ctx context.Context, arg UpdateFuttersorteParams) (Futtersorten, error)
	UpdateGewichtTabelle(ctx context.Context, arg UpdateGewichtTabelleParams) (Gewichttabelle, error)
	UpdateHerde(ctx context.Context, arg UpdateHerdeParams) (Herden, error)
	UpdateHerdeStock(ctx context.Context, arg UpdateHerdeStockParams) error
	UpdateKosten(ctx context.Context, arg UpdateKostenParams) (Kosten, error)
	UpdateKostentabkopf(ctx context.Context, arg UpdateKostentabkopfParams) (Kostentabkopf, error)
	UpdateLSLKlassik(ctx context.Context, arg UpdateLSLKlassikParams) (Lslklassik, error)
	UpdateLagerplatz(ctx context.Context, arg UpdateLagerplatzParams) (Lagerplatz, error)
	UpdateMwst(ctx context.Context, arg UpdateMwstParams) (Mwst, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	UpdateRasse(ctx context.Context, arg UpdateRasseParams) (Rasse, error)
	UpdateShowTV(ctx context.Context, arg UpdateShowTVParams) (Showtv, error)
	UpdateSilo(ctx context.Context, arg UpdateSiloParams) (Silo, error)
	UpdateStall(ctx context.Context, arg UpdateStallParams) (Stall, error)
	UpdateTabellenkopf(ctx context.Context, arg UpdateTabellenkopfParams) (Tabellenkopf, error)
	UpdateText(ctx context.Context, arg UpdateTextParams) (Texte, error)
	UpdateTextTyp(ctx context.Context, arg UpdateTextTypParams) (TextTypen, error)
	UpdateTierbewegung(ctx context.Context, arg UpdateTierbewegungParams) (Tierbewegungen, error)
	UpdateUebersetzung(ctx context.Context, arg UpdateUebersetzungParams) (Uebersetzungen, error)
	UpdateVerkauf(ctx context.Context, arg UpdateVerkaufParams) (Verkauf, error)
	UpsertFieldTranslation(ctx context.Context, arg UpsertFieldTranslationParams) (Translatefeldnamen, error)
	UpsertUebersetzung(ctx context.Context, arg UpsertUebersetzungParams) (Uebersetzungen, error)
}

var _ Querier = (*Queries)(nil)
