// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repo_mysql

import (
	"database/sql"
)

type Aktionen struct {
	ID               int32          `json:"id"`
	AktionenKz       sql.NullString `json:"aktionen_kz"`
	IDUser           sql.NullInt32  `json:"id_user"`
	Aktionsdatum     sql.NullString `json:"aktionsdatum"`
	Bezeichnung      sql.NullString `json:"bezeichnung"`
	IntervallTage    sql.NullInt32  `json:"intervall_tage"`
	AnzahlIntervalle sql.NullInt32  `json:"anzahl_intervalle"`
	Erledigt         sql.NullInt32  `json:"erledigt"`
	IDUserErledigt   sql.NullInt32  `json:"id_user_erledigt"`
	ErledigtAm       sql.NullString `json:"erledigt_am"`
	Bemerkung        sql.NullString `json:"bemerkung"`
}

type Benutzer struct {
	ID                int32  `json:"id"`
	Username          string `json:"username"`
	Passwort          string `json:"passwort"`
	Klarname          string `json:"klarname"`
	IDBenutzerProfile int32  `json:"id_benutzer_profile"`
}

type Benutzerprofile struct {
	ID                      int32  `json:"id"`
	ProfilKz                string `json:"profil_kz"`
	Beschreibung            string `json:"beschreibung"`
	FDashboard              int32  `json:"f_dashboard"`
	FHerdenVerwalten        int32  `json:"f_herden_verwalten"`
	FEinrichtungenVerwalten int32  `json:"f_einrichtungen_verwalten"`
	FPersonenVerwalten      int32  `json:"f_personen_verwalten"`
	FBuchungenErfassen      int32  `json:"f_buchungen_erfassen"`
	FAuswertungenAnzeigen   int32  `json:"f_auswertungen_anzeigen"`
	FSqlStrukturVerwalten   int32  `json:"f_sql_struktur_verwalten"`
	FBenutzerProfile        int32  `json:"f_benutzer_profile"`
	FParameterEditieren     int32  `json:"f_parameter_editieren"`
	FKostenVerwalten        int32  `json:"f_kosten_verwalten"`
	FTabellenAnzeigen       int32  `json:"f_tabellen_anzeigen"`
	FTexteVerwalten         int32  `json:"f_texte_verwalten"`
	FSystemVerwaltung       int32  `json:"f_system_verwaltung"`
	FBackupErstellen        int32  `json:"f_backup_erstellen"`
}

type Buchung struct {
	ID              int32   `json:"id"`
	IDHerden        int32   `json:"id_herden"`
	Lw              int32   `json:"lw"`
	Herdennummer    int32   `json:"herdennummer"`
	Buchungsdatum   string  `json:"buchungsdatum"`
	Gewichtprobe    int32   `json:"gewichtprobe"`
	Kontrollgewicht float64 `json:"kontrollgewicht"`
	Klassea         int32   `json:"klassea"`
	Verluste        int32   `json:"verluste"`
	Eimasse         float64 `json:"eimasse"`
	Schmutz         int32   `json:"schmutz"`
	Knickeier       int32   `json:"knickeier"`
	Vollei          float64 `json:"vollei"`
	Brucheier       int32   `json:"brucheier"`
	Tierbestand     int32   `json:"tierbestand"`
	IDEitabelle     int32   `json:"id_eitabelle"`
	IDDgewichttab   int32   `json:"id_dgewichttab"`
	Futterktag      int32   `json:"futterktag"`
	Silonr          int32   `json:"silonr"`
	Kl6             int32   `json:"kl6"`
	Vermitteltam    string  `json:"vermitteltam"`
	Small           int32   `json:"small"`
	Large           int32   `json:"large"`
	Medium          int32   `json:"medium"`
	Xl              int32   `json:"xl"`
	Zeitstempel     string  `json:"zeitstempel"`
	Dgewichtei      float64 `json:"dgewichtei"`
	Aw              int32   `json:"aw"`
	Vermittelt      string  `json:"vermittelt"`
	Futterverbrauchtier int32   `json:"futterverbrauchtier"`
}

type DynamischeSql struct {
	ID                 int32  `json:"id"`
	Beschreibung       string `json:"beschreibung"`
	Sqlstatement       string `json:"sqlstatement"`
	KategorieKz        string `json:"kategorie_kz"`
	GruppenKz          string `json:"gruppen_kz"`
	TypKz              string `json:"typ_kz"`
	TemplateName       string `json:"template_name"`
	ParamDef           string `json:"param_def"`
	DetailSql          string `json:"detail_sql"`
	LinkLogic          string `json:"link_logic"`
	GroupField         string `json:"group_field"`
	RowsPerPage        int32  `json:"rows_per_page"`
	PageOrientation    string `json:"page_orientation"`
	ShowMasterGrid     int32  `json:"show_master_grid"`
	ShowDetailGrid     int32  `json:"show_detail_grid"`
	SystemKz           string `json:"system_kz"`
	SqlstatementNative string `json:"sqlstatement_native"`
	DetailSqlNative    string `json:"detail_sql_native"`
	RootKz             string `json:"root_kz"`
	Summenzeile        string `json:"summenzeile"`
	IstSummenzeile     int32  `json:"ist_summenzeile"`
}

type Eierpreise struct {
	ID            int32   `json:"id"`
	KzHaltungstyp string  `json:"kz_haltungstyp"`
	Eierklasse    string  `json:"eierklasse"`
	GewichtVon    float64 `json:"gewicht_von"`
	GewichtBis    float64 `json:"gewicht_bis"`
	PreisVon      float64 `json:"preis_von"`
	PreisBis      float64 `json:"preis_bis"`
}

type Eilager struct {
	ID            int32   `json:"id"`
	Lagernummer   int32   `json:"lagernummer"`
	Kz            string  `json:"kz"`
	Bezeichnung   string  `json:"bezeichnung"`
	LetzteBuchung string  `json:"letzte_buchung"`
	Jumbos        int32   `json:"jumbos"`
	Xl            int32   `json:"xl"`
	Large         int32   `json:"large"`
	Medium        int32   `json:"medium"`
	Small         int32   `json:"small"`
	Volleikg      float64 `json:"volleikg"`
	Klasse6       string  `json:"klasse6"`
	Klasse7       string  `json:"klasse7"`
	Aw            int32   `json:"aw"`
}

type Eilagerbuchung struct {
	ID              int32   `json:"id"`
	IDFremdeslager  int32   `json:"id_fremdeslager"`
	IDBuchung       int32   `json:"id_buchung"`
	IDEilager       int32   `json:"id_eilager"`
	Buchungsdatum   string  `json:"buchungsdatum"`
	Jumbos          int32   `json:"jumbos"`
	Xl              int32   `json:"xl"`
	Large           int32   `json:"large"`
	Medium          int32   `json:"medium"`
	Small           int32   `json:"small"`
	Volleikg        float64 `json:"volleikg"`
	Schmutz         int32   `json:"schmutz"`
	Knickeier       int32   `json:"knickeier"`
	Brucheier       int32   `json:"brucheier"`
	Buchungstyp     string  `json:"buchungstyp"`
	Charge          string  `json:"charge"`
	KzLager         string  `json:"kz_lager"`
	IDFremdebuchung int32   `json:"id_fremdebuchung"`
	Verkauf         int32   `json:"verkauf"`
}

type FeldKatalog struct {
	ID       int32  `json:"id"`
	Kz       string `json:"kz"`
	Feldname string `json:"feldname"`
	Nameindb int32  `json:"nameindb"`
}

type Firmenparameter struct {
	ID                        int32   `json:"id"`
	IDHerden                  int32   `json:"id_herden"`
	Kz                        string  `json:"kz"`
	Jumbos                    int32   `json:"jumbos"`
	Klassenerfassen           int32   `json:"klassenerfassen"`
	Klasseaerfassen           int32   `json:"klasseaerfassen"`
	Klasseaerrechnen          int32   `json:"klasseaerrechnen"`
	Klasseavermitteln         int32   `json:"klasseavermitteln"`
	Erfasseschmutzei          int32   `json:"erfasseschmutzei"`
	Erfasseknickei            int32   `json:"erfasseknickei"`
	Erfassebruchei            int32   `json:"erfassebruchei"`
	Erfassevollei             int32   `json:"erfassevollei"`
	Massvollei                int32   `json:"massvollei"`
	Aufteilunggewicht         int32   `json:"aufteilunggewicht"`
	Kontrollwiegung           int32   `json:"kontrollwiegung"`
	Anzahlkontrollw           int32   `json:"anzahlkontrollw"`
	Verpackungkg              float64 `json:"verpackungkg"`
	Aufteilungalter           int32   `json:"aufteilungalter"`
	Erfassevolleikg           int32   `json:"erfassevolleikg"`
	Laufzeitwochen            int32   `json:"laufzeitwochen"`
	Zeitstempel               string  `json:"zeitstempel"`
	Schlachterloeshenne       float64 `json:"schlachterloeshenne"`
	Produktionsdauer          int32   `json:"produktionsdauer"`
	IDTabellegewicht          int32   `json:"id_tabellegewicht"`
	IDTabellealter            int32   `json:"id_tabellealter"`
	LegebeginnLw              int32   `json:"legebeginn_lw"`
	Verlustebeibuchung        int32   `json:"verlustebeibuchung"`
	Lagerbuchungbeibuchung    int32   `json:"lagerbuchungbeibuchung"`
	Aw                        int32   `json:"aw"`
	Maxtagevermitteln         int32   `json:"maxtagevermitteln"`
	Chargejumbos              int32   `json:"chargejumbos"`
	Chargexl                  int32   `json:"chargexl"`
	Chargemedium              int32   `json:"chargemedium"`
	Chargesmall               int32   `json:"chargesmall"`
	Chargelarge               int32   `json:"chargelarge"`
	Chargevollei              int32   `json:"chargevollei"`
	Chargeprefixfirma         string  `json:"chargeprefixfirma"`
	Chargeprefixherdennummer  int32   `json:"chargeprefixherdennummer"`
	Chargedatum               int32   `json:"chargedatum"`
	Chargelagernummer         int32   `json:"chargelagernummer"`
	Chargetrennung            string  `json:"chargetrennung"`
	Beivermittelndatumaktuell int32   `json:"beivermittelndatumaktuell"`
	Pseudolager               int32   `json:"pseudolager"`
	Bio                       int32   `json:"bio"`
	Haltungstyp               string  `json:"haltungstyp"`
	Bioaufschlag              float64 `json:"bioaufschlag"`
	Futterinventur            int32   `json:"futterinventur"`
}

type Futter struct {
	ID             int32   `json:"id"`
	IDSilo         int32   `json:"id_silo"`
	Silonummer     int32   `json:"silonummer"`
	Herdenr        int32   `json:"herdenr"`
	IDPerson       int32   `json:"id_person"`
	Lieferdatum    string  `json:"lieferdatum"`
	Liefermenge    float64 `json:"liefermenge"`
	Preisdt        float64 `json:"preisdt"`
	Rabattproz     float64 `json:"rabattproz"`
	Netto          float64 `json:"netto"`
	Brutto         float64 `json:"brutto"`
	Mwstproz       float64 `json:"mwstproz"`
	Mwstkz         string  `json:"mwstkz"`
	Datum          string  `json:"datum"`
	Zeitstempel    string  `json:"zeitstempel"`
	IDFuttersorten int32   `json:"id_futtersorten"`
	Aw             int32   `json:"aw"`
}

type Futtersorten struct {
	ID          int32  `json:"id"`
	Bezeichnung string `json:"bezeichnung"`
}

type Gewichttabelle struct {
	ID             int32   `json:"id"`
	Tabellennummer int32   `json:"tabellennummer"`
	Eigewicht      float64 `json:"eigewicht"`
	Klasse1        float64 `json:"klasse1"`
	Klasse2        float64 `json:"klasse2"`
	Klasse3        float64 `json:"klasse3"`
	Klasse4        float64 `json:"klasse4"`
	Klasse5        float64 `json:"klasse5"`
	Klasse6        float64 `json:"klasse6"`
	Klasse7        float64 `json:"klasse7"`
}

type Herden struct {
	ID                    int32   `json:"id"`
	IDSilo                int32   `json:"id_silo"`
	IDStall               int32   `json:"id_stall"`
	IDEilager             int32   `json:"id_eilager"`
	IDGewichttab          int32   `json:"id_gewichttab"`
	IDZuechter            int32   `json:"id_zuechter"`
	IDRasse               int32   `json:"id_rasse"`
	Herdennummer          int32   `json:"herdennummer"`
	Bezeichnung           string  `json:"bezeichnung"`
	Anfangskosten         int32   `json:"anfangskosten"`
	Anfangsbestand        int32   `json:"anfangsbestand"`
	Einstalldatum         string  `json:"einstalldatum"`
	Legedatum             string  `json:"legedatum"`
	Einstallkosten        float64 `json:"einstallkosten"`
	Datum                 string  `json:"datum"`
	Zeitstempel           string  `json:"zeitstempel"`
	Aktiv                 int32   `json:"aktiv"`
	Aw                    int32   `json:"aw"`
	Allebuchungenmitdatum int32   `json:"allebuchungenmitdatum"`
}

type Klassifizierung struct {
	ID          int32   `json:"id"`
	Preis       float64 `json:"preis"`
	Klasse      string  `json:"klasse"`
	Von         int32   `json:"von"`
	Bis         int32   `json:"bis"`
	Bemerkung   string  `json:"bemerkung"`
	Zeitstempel string  `json:"zeitstempel"`
	Aw          int32   `json:"aw"`
}

type Kosten struct {
	ID              int32   `json:"id"`
	IDKostentabkopf int32   `json:"id_kostentabkopf"`
	Kostentyp       string  `json:"kostentyp"`
	Bezeichnung     string  `json:"bezeichnung"`
	Kosten          float64 `json:"kosten"`
	Tage            int32   `json:"tage"`
	Buchungsdatum   string  `json:"buchungsdatum"`
	Aw              int32   `json:"aw"`
}

type Kostentabkopf struct {
	ID               int32   `json:"id"`
	Schlachterloes   float64 `json:"schlachterloes"`
	Proddauergeplant int32   `json:"proddauergeplant"`
	Gebaeudewert     float64 `json:"gebaeudewert"`
	AbschreibungG    float64 `json:"abschreibung_g"`
	Geraetewert      float64 `json:"geraetewert"`
	AbschreibungR    float64 `json:"abschreibung_r"`
	Kostentag        float64 `json:"kostentag"`
	Aw               int32   `json:"aw"`
}

type Lagerplatz struct {
	ID          int32  `json:"id"`
	IDEilager   int32  `json:"id_eilager"`
	Bezeichnung string `json:"bezeichnung"`
	Bemerkung   string `json:"bemerkung"`
}

type Lslklassik struct {
	ID             int32   `json:"id"`
	Tabellennummer int32   `json:"tabellennummer"`
	Alterinwochen  int32   `json:"alterinwochen"`
	Eizahlkum      float64 `json:"eizahlkum"`
	Legerateah     float64 `json:"legerateah"`
	Legeratedh     float64 `json:"legeratedh"`
	Eigewichtwo    float64 `json:"eigewichtwo"`
	Eigewichtkum   float64 `json:"eigewichtkum"`
	Eimassewo      float64 `json:"eimassewo"`
	Eimassekum     float64 `json:"eimassekum"`
	Aw             int32   `json:"aw"`
}

type Mwst struct {
	ID      int32   `json:"id"`
	Mwstkz  string  `json:"mwstkz"`
	Prozent float64 `json:"prozent"`
	Konto   string  `json:"konto"`
	Aw      int32   `json:"aw"`
}

type Person struct {
	ID             int32          `json:"id"`
	IDTexte        int32          `json:"id_texte"`
	IDAnrede       int32          `json:"id_anrede"`
	Personennummer int32          `json:"personennummer"`
	Postfach       string         `json:"postfach"`
	Name           string         `json:"name"`
	Firma          string         `json:"firma"`
	Strasse        string         `json:"strasse"`
	Plz            string         `json:"plz"`
	Ort            string         `json:"ort"`
	Telefon        string         `json:"telefon"`
	Mobiltelephon  string         `json:"mobiltelephon"`
	Email          string         `json:"email"`
	Email2         string         `json:"email2"`
	Foto           sql.NullString `json:"foto"`
	Kz             string         `json:"kz"`
	Homepage       string         `json:"homepage"`
}

type Rasse struct {
	ID    int32  `json:"id"`
	Rasse string `json:"rasse"`
	Aw    int32  `json:"aw"`
}

type Showtv struct {
	ID     int32  `json:"id"`
	Tvname string `json:"tvname"`
	Showit int32  `json:"showit"`
}

type Silo struct {
	ID                 int32  `json:"id"`
	Silonummer         int32  `json:"silonummer"`
	Personennummer     int32  `json:"personennummer"`
	IDLieferant        int32  `json:"id_lieferant"`
	Bezeichnung        string `json:"bezeichnung"`
	Inventurdatumalt   string `json:"inventurdatumalt"`
	Inventurdatumneu   string `json:"inventurdatumneu"`
	Maxfuellmenge      int32  `json:"maxfuellmenge"`
	Minfuellmenge      int32  `json:"minfuellmenge"`
	Inventurfuellmenge int32  `json:"inventurfuellmenge"`
	Aw                 int32  `json:"aw"`
}

type Stall struct {
	ID          int32  `json:"id"`
	IDAlt       int32  `json:"id_alt"`
	Stallnummer int32  `json:"stallnummer"`
	Bezeichnung string `json:"bezeichnung"`
}

type Systemsettings struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Tabellenkopf struct {
	ID             int32  `json:"id"`
	Tabellentyp    string `json:"tabellentyp"`
	Tabellennummer int32  `json:"tabellennummer"`
	Bezeichnung    string `json:"bezeichnung"`
	Anlagedatum    string `json:"anlagedatum"`
	Datum          string `json:"datum"`
}

type TextTypen struct {
	ID          int32  `json:"id"`
	Kz          string `json:"kz"`
	Bezeichnung string `json:"bezeichnung"`
	SystemKz    int32  `json:"system"`
	Status      int32  `json:"status"`
}

type Texte struct {
	ID        int32  `json:"id"`
	TextTypKz string `json:"text_typ_kz"`
	Kz        string `json:"kz"`
	SystemKz  int32  `json:"system"`
	Status    int32  `json:"status"`
}

type Tierbewegungen struct {
	ID             int32          `json:"id"`
	Herdennummer   sql.NullInt32  `json:"herdennummer"`
	IDBuchung      sql.NullInt32  `json:"id_buchung"`
	Typ            sql.NullString `json:"typ"`
	IDTexte        sql.NullInt32  `json:"id_texte"`
	Bewegungsdatum sql.NullString `json:"bewegungsdatum"`
	Bewegungen     sql.NullInt32  `json:"bewegungen"`
	IDHerdenVon    sql.NullInt32  `json:"id_herden_von"`
	IDHerdenNach   sql.NullInt32  `json:"id_herden_nach"`
	Kosten         sql.NullString `json:"kosten"`
}

type Translatefeldnamen struct {
	IDFeldKatalog int32  `json:"id_feld_katalog"`
	SpracheKz     string `json:"sprache_kz"`
	Betreff       string `json:"betreff"`
	Inhalt        string `json:"inhalt"`
}

type Uebersetzungen struct {
	IDTexte   int32  `json:"id_texte"`
	SpracheKz string `json:"sprache_kz"`
	Betreff   string `json:"betreff"`
	Inhalt    string `json:"inhalt"`
}

type UserState struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

type Verkauf struct {
	ID               int32   `json:"id"`
	IDEilagerbuchung int32   `json:"id_eilagerbuchung"`
	IDBuchung        int32   `json:"id_buchung"`
	Buchungsdatum    string  `json:"buchungsdatum"`
	Mengesmall       int32   `json:"mengesmall"`
	Mengemedium      int32   `json:"mengemedium"`
	Mengelarge       int32   `json:"mengelarge"`
	Mengexl          int32   `json:"mengexl"`
	Preissmall       float64 `json:"preissmall"`
	Preismedium      float64 `json:"preismedium"`
	Preislarge       float64 `json:"preislarge"`
	Preisxl          float64 `json:"preisxl"`
	Gesamtpreis      float64 `json:"gesamtpreis"`
	Bio              bool    `json:"bio"`
	Verbucht         bool    `json:"verbucht"`
	Charge           string  `json:"charge"`
	Rabattprozent    float64 `json:"rabattprozent"`
}

type Verluste struct {
	ID             int32  `json:"id"`
	IDHerden       int32  `json:"id_herden"`
	Verluste       int32  `json:"verluste"`
	Herdennummer   int32  `json:"herdennummer"`
	Typ            string `json:"typ"`
	Grund          int32  `json:"grund"`
	Bewegungsdatum string `json:"bewegungsdatum"`
	Aw             int32  `json:"aw"`
}
