// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetDBStatus():Promise<Record<string, string>>;

export function GetHelpContent():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenHelp():Promise<string>;

export function Quit():Promise<void>;

export function SaveWindowState(arg1:context.Context,arg2:string):Promise<void>;
