// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetAPIPort():Promise<number>;

export function GetDBStatus():Promise<Record<string, string>>;

export function GetLauncherPort():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function IsTestDB():Promise<boolean>;

export function OpenHelp(arg1:string):Promise<string>;

export function OpenHelpFile(arg1:string,arg2:boolean):Promise<string>;

export function Quit():Promise<void>;

export function SaveWindowState(arg1:context.Context,arg2:string):Promise<void>;

export function ToggleTestDB(arg1:boolean):Promise<string>;
