// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDBStatus() {
  return window['go']['main']['App']['GetDBStatus']();
}

export function GetHelpContent(arg1) {
  return window['go']['main']['App']['GetHelpContent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenHelp(arg1) {
  return window['go']['main']['App']['OpenHelp'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveWindowState(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2);
}
