// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIPort() {
  return window['go']['main']['App']['GetAPIPort']();
}

export function GetBaseLink() {
  return window['go']['main']['App']['GetBaseLink']();
}

export function GetCLILanguage() {
  return window['go']['main']['App']['GetCLILanguage']();
}

export function GetDBStatus() {
  return window['go']['main']['App']['GetDBStatus']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLauncherPort() {
  return window['go']['main']['App']['GetLauncherPort']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsTestDB() {
  return window['go']['main']['App']['IsTestDB']();
}

export function OpenHelp(arg1) {
  return window['go']['main']['App']['OpenHelp'](arg1);
}

export function OpenHelpFile(arg1, arg2) {
  return window['go']['main']['App']['OpenHelpFile'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveWindowState(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2);
}

export function SelectBackupDirectory(arg1) {
  return window['go']['main']['App']['SelectBackupDirectory'](arg1);
}

export function ToggleTestDB(arg1) {
  return window['go']['main']['App']['ToggleTestDB'](arg1);
}
